### ISSUE TITLE
Use a release branch to deploy production

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#1032]
- [x] Create a `release` branch
- [x] PR
  - [x] Add a release CI step that does a `git reset --hard master` on the `release` branch
  - [x] Delete manual deploy CI steps
- [x] Configure Netlify to deploy from `release` in production and `master` for sandbox
- [ ] Configure Heroku deploy from `release` in production and `master` for sandbox
- [ ] Remove unused Github secrets

**Comment by AlmightyYakob** [comment]
This has been addressed except for Heroku, due to the recent [incident](https://status.heroku.com/incidents/2413).
