### ISSUE TITLE
Profile the asset paths endpoint to determine cause of high memory usage

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#1055]
The paths endpoint has performance issues on dandiset 26 in production. It either takes upwards of 20+ seconds to return a response, or it ends up exceeding the available memory on the Heroku dyno and Heroku kills the request. 

What needs to be done -

- [ ] Augment `import_dandisets.py` so that it can import assets from production. There's no need to clone the S3 files, we can simply substitute empty files for those to avoid needing to download significant amounts of data
- [ ] Clone dandiset 26 into a local instance and profile the endpoint's performance with it

**Comment by yarikoptic** [comment]
just re-sharing the news @satra and others shared about fresh open-sourcing of a memory profiler for Python https://github.com/bloomberg/memray which sounds like might be of help here.

**Comment by waxlamp** [comment]
@mvandenburgh, what's the current status here?
