### ISSUE TITLE
With empty datasets visible, sorting by size doesn't work

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1059]
see https://dandiarchive.org/dandiset?page=1&sortOption=3&sortDir=-1 -- is the view where sorting should have largest dandisets first, but whenever showing empty dandisets is enabled -- those 0 size dandisets are shown first

**Comment by waxlamp** [comment]
Nice find!

**Comment by waxlamp** [comment]
This seems to have been fixed--empty dandisets show up in the last pages instead of the first.
