### ISSUE TITLE
add some "stable" web elements to signal begin/end of loading the page for benchmarking

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1060]
I am trying to address https://github.com/dandi/dandi-api-webshots-tools/issues/16 in that behavior of web front end has changed from its past which makes it harder to automate timing of loading the pages.

Before now we relied on progress bar elements to appear first (`v-progress-circular` or `v-progress-linear` ) and they did that very well and rapidly, so we just waited for them to disappear.  Now 
- it might take a second or two for them to appear at all, e.g. visit https://dandiarchive.org/dandiset/000026/draft/files?location= -- takes a bit for me 
- or they might not even appear (I believe that happens in https://dandiarchive.org/dandiset/000155/draft/files?location=),
- or they seems no longer be shown at all for landing page, e.g. https://dandiarchive.org/dandiset/000026, although it does take a bit to load it
- making it impossible to actually tell reliably (without "let's wait for a few seconds first") either what we see on screen is the final rendering even if empty (e.g. https://dandiarchive.org/dandiset/000155/draft/files?location=)

So, I thought -- could there be some web element populated in the screen which would just signal -- I am done rendering this page.  

Meanwhile I am trying out an ugly workaround in https://github.com/dandi/dandi-api-webshots-tools/pull/18

**Comment by waxlamp** [comment]
I don't believe this is possible in general. (If someone knows of a way, please speak up.) The problem is that the standard tools (like `onload` callbacks) don't account for dynamic page updates, and Vue is just one big bundle of dynamic page updates.

Unfortunately you may be stuck with "ugly workarounds".
