### ISSUE TITLE
Consider making versioned dependency on dandischema more flexible and import its version variable

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1078]
see https://github.com/dandi/dandi-archive/pull/1074#issuecomment-1115233452 for context

**Comment by waxlamp** [comment]
What is the status of this issue? @AlmightyYakob provided some good guidelines in the linked comment, and offered to push a change to fix this issue, but I am not sure if that was done or where the PR is.

**Comment by AlmightyYakob** [comment]
I'm not sure what this issue is for. As far as I can tell, #1074 addresses this.

**Comment by yarikoptic** [comment]
hm... this issue was created to go along with the next comment in that PR https://github.com/dandi/dandi-archive/pull/1074#issuecomment-1116160302 so that PR could not address it. But I fail to fully comprehend what I meant back then - it was relating though to dandi-cli tests failing to test against that PR changes since ` `pip install "dandi[test]"` was installing ` dandischema~=0.6.0` at that point in time whenever here server would using 0.7.0 (and running in a docker).  I might have said that "server should allow upload of older versions of dandischema" but I think it already does that ... since I lost already track on what I had in mind, let's close until some clarity comes back ;)
