### ISSUE TITLE
staging deployment has failed

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1079]
After #1074 I expected a new (0.7.1) version of dandischema be used, but saw
```
$> curl -s -X GET "https://api-staging.dandiarchive.org/api/info/" -H "accept: application/json" | jq '.schema_version'
"0.6.2"
```
and apparently release action has failed https://github.com/dandi/dandi-archive/runs/6274814696?check_suite_focus=true 

```
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:2541b1294d2704b0964813337f33b291d3f8596b)
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/2541b1294d2704b0964813337f33b291d3f8596b'. Error: The SSL connection could not be established, see inner exception.
Warning: Back off 13.193 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/2541b1294d2704b096481[33](https://github.com/dandi/dandi-archive/runs/6274814696?check_suite_focus=true#step:1:33)37f33b291d3f8596b'. Error: The SSL connection could not be established, see inner exception.
Warning: Back off 21.039 seconds before retry.
```

I don't see anything special coded in that (?) https://github.com/dandi/dandi-archive/blob/HEAD/.github/workflows/backend-staging-deploy.yml . @jwodder @waxlamp -- any ideas on what could have went wrong?!

**Comment by jwodder** [comment]
@yarikoptic The release failure looks like an internal GitHub Actions issue.  Try re-running the job.

**Comment by yarikoptic** [comment]
yeap , did just that and it presumably released fine!  I got mislead though by a version -- now it reports
```
$> curl -s -X GET "https://api-staging.dandiarchive.org/api/info/" -H "accept: application/json" | jq '.schema_version'
"0.6.3"
```
which is good, but i was expecting 0.7.1 which is of the library, which we do not show there. So all is good AFAIK.
