### ISSUE TITLE
Do we re-validate dandisets upon dandischema upgrade?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1080]
Was troubleshooting https://github.com/dandi/dandi-archive/issues/961 . dandischema was upgraded in staging. But the error remains the same (e.g. see / visit https://gui-staging.dandiarchive.org/dandiset/200418).  So the question is - does server automagically revalidates all dandisets?

For now I edited metadata, which I guess should have triggered revalidation but I waited for a bit and error message is the same ,and it is in particular odd because url is actually

```
$> grep url dandiset\ \(1\).json
  "url": "https://gui-staging.dandiarchive.org/dandiset/200418/draft",
```
if I download metadata while error says:

![image](https://user-images.githubusercontent.com/39889/166573375-a84cf12e-fee8-46c7-904e-c0ef85c07b6e.png)

**Comment by waxlamp** [comment]
@mvandenburgh, can you answer Yarik's question?

**Comment by mvandenburgh** [comment]
Closing this issue as the original question was answered.
