### ISSUE TITLE
Deploy previews are "canceled"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1083]
wanted to look at preview in https://github.com/dandi/dandi-archive/pull/1077 but although green, says "Canceled" and https://app.netlify.com/sites/gui-staging-dandiarchive-org/deploys/6270530cfac5b2000a47a0a1 says:

```
5:54:50 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'web/dist' versus 'dist' in the Netlify UI
5:54:50 PM: No changes detected in base directory. Returning early from build.
5:54:50 PM: Creating deploy upload records
5:54:50 PM: Failed during stage 'checking build content for changes': Canceled build due to no content change
5:54:51 PM: Finished processing build request in 28.753838385s
```

so I wonder if that is that `web/dist` vs `dist` or smth else?

**Comment by AlmightyYakob** [comment]
If nothing in the `web` directory changed, the deploy preview is cancelled, as it would have no effect.

**Comment by AlmightyYakob** [comment]
It still wouldn't have any affect, as the deploy preview is pointed at staging, which doesn't contain the changes of the relevant PR (yet).

**Comment by yarikoptic** [comment]
actually -- we can't really afford running a new dandi-api per each PR, so there can't be such fancy preview. Ok - let's just close, thanks @AlmightyYakob
