### ISSUE TITLE
add force reingest option for zarr archives

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#1091]
ingest currently has no way of knowing that files have been updated behind the scenes through out of band process for example. a force parameter would trigger a reingest when the database thinks it should not be.

**Comment by waxlamp** [comment]
Possible strategies:
- write a management script that triggers the reingest process (Jake may have already written such a script)
- give dandiset owners (and admins) a button to trigger the process on a given Zarr

**Comment by AlmightyYakob** [comment]
> Possible strategies:
> 
> * write a management script that triggers the reingest process (Jake may have already written such a script)

This already exists: https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/management/commands/ingest_zarr_archive.py

> * give dandiset owners (and admins) a button to trigger the process on a given Zarr

This exists but only in the admin panel 
![Screenshot from 2022-06-29 14-25-38](https://user-images.githubusercontent.com/11370025/176509369-4f6a5d15-88f5-42bf-9b62-08f7e334c7ef.png)

Should we add something in the GUI for this as well?

**Comment by satra** [comment]
before we make any changes to the gui, we will want a mechanism for celery task queue monitoring by job/owner id. so i would think this would be a new component of the gui related to tasks running on dandisets.
