### ISSUE TITLE
WEB UI release deploy is "off"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1100]
besides odd reporting (#1089) it seems simply off.  E.g. we have just merged #1099 which triggered release of 0.2.22 so that
```
$> curl -s https://dandiarchive.org/server-info | jq '.version'
"0.2.22"
```
and staging
```
$> curl -s https://gui-staging.dandiarchive.org/server-info | jq '.version'
"0.2.21.post2+g29544680"
```
which is the same (but different due to what I describe in #1089).

But WEB UI versions are completely off.

- staging web ui reports [v0.1.36-2489-ge36085f4](https://github.com/dandi/dandi-archive/commit/e36085f4d9a15c5c35725e89a4af76c4551d9d7b) which is 

```
$> git describe e36085f4
v0.2.21
```
- production instance web ui reports [v0.2.12-24-g12e1c5e1](https://github.com/dandi/dandi-archive/commit/12e1c5e146bf046b68e933c4a8e628afc4a3e0a0) which is

```
$> git describe 12e1c5e146bf046b68e933c4a8e628afc4a3e0a0
v0.2.13
```
!!!! so obviously web UI is not deployed "properly" neither for staging nor for production!  We need to fix it before some backward incompatible change in dandi-api!  Any help/pointers would be welcome!

edit 1: We have http://github.com/dandi/dandi-archive/blob/HEAD/doc/design/deployment-1.md describing "howto", and talks about "release" branch which we do update so all should be good (but it is not, and not yet clear why 1 release off for staging)

**Comment by jwodder** [comment]
@yarikoptic You can set the commit message for the CHANGELOG update by passing `--message=$NEW_COMMIT_MESSAGE` to `auto shipit`.

**Comment by yarikoptic** [comment]
thanks @jwodder -- I will try that!

**Comment by yarikoptic** [comment]
I think that #1101 resolved it to the degree it could!  It triggered the build which was canceled since no changes to `web/` and thus version displayed on website didn't change.

![image](https://user-images.githubusercontent.com/39889/168123665-736a1b0c-7348-4904-ba4e-4dabefd6caf2.png)
