### ISSUE TITLE
/zarr/{zarr_id}/upload/ -- allow for two parallel upload batches.

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1105]
one of the slowdowns for uploads is the need to wait for prior upload to finish before requesting next batch of the upload URLs.  Allowing for up to two batches would allow for upload to request next batch right after initiating upload of the initial/prior batch.  `/complete` endpoint would operate on the 1st of the possible two active upload batches, removing it from the "queue" (of size 2) thus allowing for the next batch to be requested and added to that queue. 

in principle such paradigm can be generalized to the queue longer than 2 active batches but I do not think we would need that, but code could be generic for a batches queue of a specific size (in our case - `2`).

**Comment by waxlamp** [comment]
How much time would this save? Is requesting the batch of presigned upload URLs particularly slow?

**Comment by danlamanna** [comment]
Fixed by #1448.
