### ISSUE TITLE
Investigate where `QuerySet.iterator()` can be used to optimize memory usage

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#1130]
There's probably some more places like #1126 where `.iterator()` can be used to make things more memory-efficient.

**Comment by waxlamp** [comment]
From the [docs](https://docs.djangoproject.com/en/4.0/ref/models/querysets/):

> For a QuerySet which returns a large number of objects that you only need to access once, this can result in better performance and a significant reduction in memory.

I am certain we run into this exact condition at multiple places in our codebase. Let's go hunting for them!

**Comment by brianhelba** [comment]
See #985. I discussed this with some developers a few months ago too.

**Comment by mvandenburgh** [comment]
This is complete and resulted in several PRs like #1126, #1161 , etc.
