### ISSUE TITLE
DELETE /uploads/{upload_id}

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#115]
so a nice client, if interrupted, could gracefully delete an ongoing upload (unless it has provisions to restart somehow)

**Comment by yarikoptic** [comment]
I think this might be nice to have implemented so that `dandi-cli` could gracefully "cancel" the upload if eg interrupted (now I guess it will just leave it for GC to pick up)

**Comment by waxlamp** [comment]
Since there is no longer a concept of an upload object, this issue is no longer valid.
