### ISSUE TITLE
Avoid race-condition for DELETE /zarr/{zarr_id}/upload/ "monitoring"?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1153]
Current design for canceling zarr upload described in https://github.com/dandi/dandi-cli/issues/929 relies on pulling and testing until `upload_in_progress == False` . It should work but opens race-condition for the client which might miss the point whenever specific zarr upload is no longer in progress but then someone else (or different thread of the same process?) requests the upload for that zarr and thus would flip that `upload_in_progress` to True again. 

I wonder if may be each upload could gain "an ID" (FWIW could be the first upload URL from the batch) which then would be used in that 

```
upload_in_progress | string title: Upload in progressreadOnly: true
```

NB note that it already says `string` not `bool` in swagger ;-)

then the client could loop until upload_in_progress is not original value, thus knowing that upload e.g. was finally canceled as it requested, but may be a new one started if it gained some new non-empty/False value.

WDYT?  or no need really @dandi/dandiarchive @jwodder ?

**Comment by AlmightyYakob** [comment]
We could include an `id` in the upload batch creation response, but that would include an ID for each file, since there's no model that represents an upload batch. Having a model that represents an upload batch might be useful though.

**Comment by waxlamp** [comment]
@yarikoptic, what is the base use case for this? That is, when is a client canceling a zarr upload, waiting to verify, and then attempting to start a new zarr upload?

**Comment by yarikoptic** [comment]
I think it applies for any zarr upload which user interrupts?  in particular after https://github.com/dandi/dandi-cli/pull/1041 improvements, where we do explicitly cancel zarr upload if upload is not completed in that run of dandi-cli.  The rationale is - to avoid https://github.com/dandi/dandi-cli/issues/1028 - i.e. users seeing "Simultaneous uploads are not allowed"  from the server while trying to reupload a zarr "file".

**Comment by yarikoptic** [comment]
@AlmightyYakob since you are now "deep in zarr" -- is this issue still pertains?

**Comment by AlmightyYakob** [comment]
I'm not sure. The original issue in https://github.com/dandi/dandi-cli/issues/1028 was addressed (zarrs not being cancelled). Beyond that, I'm not sure if anything else mentioned in the issue is relevant to this issue, or requires any intervention in the API.

**Comment by waxlamp** [comment]
With the overhaul of Zarr uploads, this is no longer relevant.
