### ISSUE TITLE
Allow zarr to be reingested even if was already ingested?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1170]
Echoing https://github.com/dandi/dandi-archive/issues/1138#issuecomment-1178053691 discussion suggesting that client might still want/need to trigger `/ingest` process and in particular having in mind that we cannot revoke upload presigned URLs (https://github.com/dandi/dandi-archive/issues/1162) and thus some "lost" client can still upload some outdated file etc, we might need a way to "force" re-ingestion of the zarr archive.  But that should not be allowed "blindly" and for everyone since open DoS attack (keep service busy reingesting) so may be more thinking is needed.  May be should be left at the level of a service script. WDYT?

**Comment by waxlamp** [comment]
A service script or an admin-only action endpoint.

**Comment by waxlamp** [comment]
@AlmightyYakob, I think this may be closeable now--can you please assess?

**Comment by AlmightyYakob** [comment]
This would still apply, but is now the `finalize` endpoint. We could gate that with a `force` flag, allowed by admins only.

**Comment by waxlamp** [comment]
I think either a button in the admin console, or even just a service script, would be the right interface to it. What do you think?

**Comment by AlmightyYakob** [comment]
> I think either a button in the admin console, or even just a service script, would be the right interface to it. What do you think?

I think that makes sense, since as a normal user, you can't update a zarr out of band, which is the only way you'd need to run this anyway. We do already have the option in the admin console, but it doesn't use the `force=True` flag, making it largely useless. I'll make a PR to fix that.
