### ISSUE TITLE
zarr read_checksum_file : robustify (or eliminate?) interactions with s3

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1180]
just got an email from Sentry about SystemExit(1) due to 

```
URL    https://api.dandiarchive.org/api/zarr/0ce332d9-ca12-4f55-9d7f-b4b7e730c6f6…                                                                                                   
Method GET       
```
looking at details on SEntry

![image](https://user-images.githubusercontent.com/39889/178342792-1084b9ed-8a12-4150-a5c4-8536ff06596d.png)

either boto doesn't really retry or doesn't retry enough times?

<details>
<summary>running the same query locally succeeds now ok</summary> 

```shell
$> curl  https://api.dandiarchive.org/api/zarr/0ce332d9-ca12-4f55-9d7f-b4b7e730c6f6/ 
{"name":"sub-MITU01/ses-20211021h20m11s22/micr/sub-MITU01_ses-20211021h20m11s22_sample-107_stain-NN_run-1_chunk-10_SPIM.ome.zarr","dandiset":"000108","zarr_id":"0ce332d9-ca12-4f55-9d7f-b4b7e730c6f6","status":"Complete","checksum":"8a1f447f699b1c10d82cdc3cc31f5b49-103043--1105189816","upload_in_progress":false,"file_count":103043,"size":1105189816}%     
```
</details>

although I am not even sure why it goes to S3, don't we have zarr checksum in the DB model???

**Comment by AlmightyYakob** [comment]
We don't currently store top level zarr checksum in DB, but I'm adding that as part of addressing https://github.com/dandi/dandi-archive/issues/1137 (along with other optimizations).

I'm going to close this since as far as I'm concerned this is duplicate, if you disagree please comment.

**Comment by yarikoptic** [comment]
Duplicate of what? If you had in mind #1137 - IMHO a different issue. Ok if a fix closes multiple issues at the same time, but I would prefer to keep a unique issue open until it is resolved

**Comment by AlmightyYakob** [comment]
The resolution to this is the same as #1137, which is currently in progress. I can keep this open until they're both closed though.

**Comment by waxlamp** [comment]
@AlmightyYakob, now that #1137 has been resolved, can this be closed as well?

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob, now that #1137 has been resolved, can this be closed as well?

Indeed it can.
