### ISSUE TITLE
Identify endpoints that call boto3 directly

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#1183]
boto3 calls should ideally only be performed in tasks, not endpoints. Every endpoint that contains a boto3 call should be identified, and have an issue filed to refactor the boto3 call into a task.

Original issue ref:

> 
> 
> > This is probably related to this.   
>    Sentry issue: [DANDI-API-9A](https://sentry.io/organizations/dandiarchive/issues/3418055784/?referrer=github_integration)
> 
> It looks like there's S3 errors happening, which is unsurprising given how unreliable networks are when hammering them with requests. We should configure boto3 retries to retry (and backoff) a bit more - https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#configuring-a-retry-mode.
> 
> Before this can be done globally, boto3 calls should be moved out of endpoints where possible.
> 
> _Originally posted by @danlamanna in https://github.com/dandi/dandi-archive/issues/1181#issuecomment-1181034266_

**Comment by waxlamp** [comment]
@mvandenburgh, is this listed as critical due to tasks crashing and gumming up the works?
