### ISSUE TITLE
support links need update on the front page of the web app

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#1188]
the support links should point to the general helpdesk, to this repo, and to the handbook. however, we also have help in the nav bar. we may need to rethink a bit about the easiest way to provide support to people.

**Comment by waxlamp** [comment]
The help link in the navbar goes here: https://github.com/dandi/helpdesk/issues/new/choose. It seems we've set up a comprehensive directory of help resources in that list of options already, including the ones you mentioned in your original issue (other than "this repo", although I wonder if that is overburdening our users--if we are aware of issues coming into the helpdesk repo, we can always route them to the appropriate repository during triage).

I will close this as completed, but please let me know if you think there are still things to be done.
