### ISSUE TITLE
Cannot spin up Dockerized environment for CLI tests

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-archive#1230]
Currently, attempting to bring up a Dockerized Dandi Archive instance using the latest dandi-archive image fails with:

```
  File "/opt/django/dandiapi/api/admin.py", line 69, in __init__
    self.actions += ['export_emails_to_csv', 'export_emails_to_plaintext']
TypeError: can only concatenate tuple (not "list") to tuple
```

**Comment by yarikoptic** [comment]
Re-triggered https://github.com/dandi/dandi-cli/pull/1003 showed them green. So #1229 should have resolved it.
