### ISSUE TITLE
Mark published blobs undeletable at the S3 level

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1237]
Came up idea from @satra during meeting with @waxlamp .  Most likely could be implemented via S3 ACL feature which seems to allow assigning keys to specific ACLs https://stackoverflow.com/questions/46800095/changing-acls-of-objects-in-an-s3-bucket-using-boto3 so we could have `published-content` ACL which would forbid deletion.

**Comment by waxlamp** [comment]
Closing in favor of #1862.
