### ISSUE TITLE
species search shows incomplete results

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1248]
How would I find all dandisets with Human data?

DANDI pulls metadata from the NWB files, and I was under the impression that these fields were included in search. If I want all dandisets that include the ElectricalSeries neurodata type, I can search for "ElectricalSeries" and this will perform as expected. 

If I search "Human", only 8 results appear, and these are the dandisets that have "Human" in the title. There are in fact 15 NWB dandisets with human data. For instance, [#4](https://dandiarchive.org/dandiset/000004) has humans but does not show up in search results. Granted, this dandiset is old, and the metadata says "Human", not "Homo sapiens - Human", but that should not affect this search.

Would it be possible to include extracted species (and all other relevant extracted metadata) in the search in addition to neurodata types?

I understand we are planning to create structured search, where searching for species is explicit, but I and likely our users would still expect the search bar to work for this.

**Comment by waxlamp** [comment]
For a quick fix, you would be ok with just searching `human` and getting back all results with `human` either in the title, or in the species field?

I think in the longer term, we are indeed hoping to understand the use cases for search better in order to determine what kind of search behavior or search "language" we should support.

**Comment by satra** [comment]
this (http://purl.obolibrary.org/obo/NCBITaxon_9606) should return any dandiset whose assetsummary metadata follow current standards. this won't include the older dandisets, whose metadata have not been updated. 

the current search simply does a text match on the metadata json. so anything in the assetsSummary would be picked up.

**Comment by bendichter** [comment]
@satra thank you, searching "http://purl.obolibrary.org/obo/NCBITaxon_9606" or "NCBITaxon_9606" does indeed return all dandisets with Human participants. 

> the current search simply does a text match on the metadata json

Yes, that was what I expected, which is why I am confused why a "Human" does not find dandiset 000004, which has "Human" in the assetSummary. 

`raw_metadata["assetsSummary"]["species"][0]["name"] == "Human"`

**Comment by bendichter** [comment]
or, wait, now it is. Was something changed?

**Comment by waxlamp** [comment]
> or, wait, now it is. Was something changed?

AFAIK, nothing changed in the deployed app between when you filed the issue and when it got "fixed". If you encounter this sort of discrepancy in the future, please do let us know.

I'll leave it to you to close this issue if you think there's nothing further to be done right now.
