### ISSUE TITLE
Asset metadata is not updated during unembargo

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandi-archive#1264]
Follow up from https://github.com/dandi/dandisets/issues/257

The asset `unembargo` method only calls save on the blob and embargoed_blob fields https://github.com/dandi/dandi-archive/blob/6134e15122e7156c718ef50b7f3bd8c9f98b6d6e/dandiapi/api/models/asset.py#L276

Because of this, the asset metadata is never repopulated, and so the old embargoed URL is still present in the metadata. Retrieving the current s3 url for any unembargoed assets that have since not been saved again, returns a path within the public bucket, not the embargoed bucket.

We should either include `metadata` in the list of fields to update, or just save the entire model.

**Comment by yarikoptic** [comment]
Thanks @AlmightyYakob ! did you trigger recomputation of sha256 in already unembargoed (e.g. those 4 in original issue) datasets?

**Comment by AlmightyYakob** [comment]
> Thanks @AlmightyYakob ! did you trigger recomputation of sha256 in already unembargoed (e.g. those 4 in original issue) datasets?

No but I'll do that now.
