### ISSUE TITLE
version api

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#1294]
the current openapi specification from the swagger docs generates the rest API as `v1`. i think we should move this to proper semantic versioning and update the version when we make changes to the API. let's start with `0.1.0` given we haven't really versioned anything till now.

**Comment by yarikoptic** [comment]
see also https://github.com/dandi/dandi-archive/issues/1203 which breadcrumbs into https://github.com/dandi/dandi-publish/issues/23 .  With that I would wholeheartedly support this initiative ;)

**Comment by satra** [comment]
let me close this in favor of #1203
