### ISSUE TITLE
SystemExit 1 on  /api/zarr/{zarr_id}/upload/complete/

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1304]
Happened for `b8b833f4-fbb0-4759-a46f-941695cd137c` zarr, was reported in Sentry, traceback was
```
SystemExit: 1
(25 additional frame(s) were not displayed)
...
  File "dandiapi/zarr/views/__init__.py", line 228, in upload_complete
    zarr_archive.complete_upload()
  File "dandiapi/zarr/models.py", line 202, in complete_upload
    etag = upload.actual_etag()
  File "dandiapi/zarr/models.py", line 66, in actual_etag
    return self.blob.storage.etag_from_blob_name(self.blob.name)
```
can't tell the reason, but wanted to leave a trail in github issues since we are troubleshooting problems with zarr uploads for @slaytonmarx in https://github.com/dandi/dandi-cli/issues/1028 and all oddities should be reported.  @dandi/dandiarchive , your feedback on what could have lead to it would be welcome!

**Comment by waxlamp** [comment]
The object in question [exists on S3](https://s3.console.aws.amazon.com/s3/object/dandiarchive?region=us-east-2&prefix=zarr/cafe6de1-1818-4f04-9bd7-4263b97480ca/0/0/0/4/3/64), so this seems like the kind of transient failure that can and does happen with distributed systems.

What's the current state of the dandiset this zarr file was being uploaded to?

**Comment by yarikoptic** [comment]
> The object in question [exists on S3](https://s3.console.aws.amazon.com/s3/object/dandiarchive?region=us-east-2&prefix=zarr/cafe6de1-1818-4f04-9bd7-4263b97480ca/0/0/0/4/3/64), so this seems like the kind of transient failure that can and does happen with distributed systems.

I would argue that they should not happen in that there should be mechanisms (locking, retries, etc) implemented to ensure that they would not happen or otherwise system would be too flaky and such errors would accumulate/draw away attention etc.

> What's the current state of the dandiset this zarr file was being uploaded to?

```
❯ curl --silent https://api.dandiarchive.org/api/zarr/b8b833f4-fbb0-4759-a46f-941695cd137c/ | jq .
{
  "name": "sub-MITU01/ses-20220316h10m52s23/micr/sub-MITU01_ses-20220316h10m52s23_sample-12_stain-LEC_run-1_chunk-1_SPIM.ome.zarr",
  "dandiset": "000108",
  "zarr_id": "b8b833f4-fbb0-4759-a46f-941695cd137c",
  "status": "Pending",
  "checksum": null,
  "upload_in_progress": false,
  "file_count": 185,
  "size": 185158418
}
```

so zarr is "Pending" (likely since awhile) although `"upload_in_progress": false,` so I guess it should be ingested?

```
❯ curl --silent https://api.dandiarchive.org/api/dandisets/000108/ | jq .
{
  "identifier": "000108",
  "created": "2021-06-01T14:35:34.166648Z",
  "modified": "2022-10-04T18:52:12.263603Z",
  "contact_person": "Kamentsky, Lee",
  "embargo_status": "OPEN",
  "most_recent_published_version": null,
  "draft_version": {
    "version": "draft",
    "name": "Light sheet imaging of the human brain",
    "asset_count": 6901,
    "size": 336460325731542,
    "status": "Valid",
    "created": "2021-06-01T14:35:34.214567Z",
    "modified": "2022-10-11T18:23:12.107263Z",
    "dandiset": {
      "identifier": "000108",
      "created": "2021-06-01T14:35:34.166648Z",
      "modified": "2022-10-04T18:52:12.263603Z",
      "contact_person": "Kamentsky, Lee",
      "embargo_status": "OPEN"
    }
  }
}
```
and @satra confirms that uploads are still ongoing.

**Comment by waxlamp** [comment]
We have a solution strategy in the works. It may involve a combination of moving some long running tasks to an async task, and putting more work on S3 rather than our own attempts to check things. Overall, the effect would be to reduce crashes and make the process more efficient.

**Comment by danlamanna** [comment]
This shouldn't be relevant with the rollout of #1448.
