### ISSUE TITLE
accessing embargoed asset as admin

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#1317]
i wasn't able to download an embargoed asset as an admin using the WebApp. i can see the dandiset, browse the files, and see asset metadata.

**Comment by waxlamp** [comment]
@satra can you verify that this is still valid? If so, can you point me to that Dandiset (which is embargoed and that we are not owners of)?

**Comment by satra** [comment]
can't replicate it now. it worked on an embargoed dandiset i checked.
