### ISSUE TITLE
Can't view metadata for embargoed assets on web UI in (i) icon forwarding to django

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1328]
clicking on (i) icon for asset at e.g. https://dandiarchive.org/dandiset/000344/draft/files?location=sub-private%2F results in django page 
at https://api.dandiarchive.org/api/dandisets/000344/versions/draft/assets/8f998a62-ac4c-465d-9989-656c90fb4668/ with

```
GET /api/dandisets/000344/versions/draft/assets/8f998a62-ac4c-465d-9989-656c90fb4668/
HTTP 401 Unauthorized
Allow: GET, PUT, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
WWW-Authenticate: Bearer realm="api"

{
    "detail": "Authentication credentials were not provided."
}
```

I am logged in user, so I guess my API_KEY (known to web UI) should be provided here while redirecting to api.dandiarchive.org or do some other needed auth dance.

**Comment by waxlamp** [comment]
Can you try logging out of the web portal and logging back in again to see if that fixes the problem? The frontend login also works for the backend, but the backend has a different expiration time for that login.

I don't consider this to be a bug in itself because it only affects admins (and we can learn how to sidestep the problem), but it is probably not good that a public-facing button links to a backend URL directly.

**Comment by waxlamp** [comment]
This does not seem to be a problem anymore--I am able to see that resource even though it's part of an embargoed dandiset.

If this is inaccurate, please re-open with specific instructions to repro.

**Comment by yarikoptic** [comment]
Going to https://dandiarchive.org/dandiset/001178/draft/files?location= and clicking on 
![image](https://github.com/user-attachments/assets/6f3b9456-84cf-4555-92e5-8443affd0253)
results in
![image](https://github.com/user-attachments/assets/3c0bc008-7ae4-402e-bca7-8099a27d2e65)

**Comment by yarikoptic** [comment]
aha -- "figured it out". IT is the same oddity which requires me to click "Django login" on swagger page to access django admin page. After I (who is super user) login to django there, I can see metadata and open for view in the browser.
