### ISSUE TITLE
Simple Dandisets on staging not validating in under two minutes

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-archive#1365]
Once again, the backups2datalad tests are failing because the test Dandisets created by the tests are not validating for publication in time.

**Comment by waxlamp** [comment]
@jwodder, can you point us to a specific failing test so we can try to see what's going on?

**Comment by jwodder** [comment]
@waxlamp https://github.com/dandi/dandisets/actions/runs/3446135222/jobs/5750937513

**Comment by yarikoptic** [comment]
citing for posterity
```
FAILED test_backups2datalad/test_core.py::test_1 - ValueError: Dandiset 205806 is Invalid: {
    "asset_validation_errors": [
        {
            "field": "new.txt",
            "message": "asset is currently being validated, please wait."
        }
    ],
    "version_validation_errors": []
}
FAILED test_backups2datalad/test_core.py::test_2 - ValueError: Dandiset 205810 is Invalid: {
    "asset_validation_errors": [
        {
            "field": "counter.txt",
            "message": "asset is currently being validated, please wait."
        }
    ],
    "version_validation_errors": []
}
FAILED test_backups2datalad/test_core.py::test_3 - ValueError: Dandiset 205812 is Invalid: {
    "asset_validation_errors": [
        {
            "field": "counter.txt",
            "message": "asset is currently being validated, please wait."
        }
    ],
    "version_validation_errors": []
}
FAILED test_backups2datalad/test_core.py::test_4 - ValueError: Dandiset 205814 is Invalid: {
    "asset_validation_errors": [
        {
            "field": "counter.txt",
            "message": "asset is currently being validated, please wait."
        }
    ],
    "version_validation_errors": []
}
=================== 4 failed, 11 passed in 684.93s (0:11:24) ===================
```

**Comment by yarikoptic** [comment]
I still wonder how we have "missed" that while testing against dandi-cli... @jwodder -- don't we have some tests in dandi-cli which would cause similar workflow?  if so -- then I guess the problem lies in the difference of "real deployment" from simple docker-compose one.

**Comment by jwodder** [comment]
@yarikoptic Yes, there are dandi-cli tests that publish Dandisets, so presumably the problem lies with the staging instance.

**Comment by yarikoptic** [comment]
is this still the case @jwodder?

**Comment by jwodder** [comment]
@yarikoptic No, this seems to have been resolved between December 5 and December 11.

**Comment by yarikoptic** [comment]
just FTR: we might be observing similar on local docker compose instance ATM:
- https://github.com/dandi/dandi-cli/issues/1488#issuecomment-2477676913
