### ISSUE TITLE
Add integration with OME-NGFF validator for .ome.zarr assets in frontend

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1371]
Eg. @satra shared in slack the URL https://ome.github.io/ome-ngff-validator/?source=https://dandiarchive.s3.amazonaws.com/zarr/78e5566d-a95e-43c4-8dc3-e96c9e9fe5c5 .  I think we should have similar URLs minted for all `.ome.zarr/` assets similarly to how we already do for .nwb and .nii.gz. This would simplify people life if they need to validate/trobleshoot zarrs in the archive.

**Comment by satra** [comment]
@yarikoptic  - this was merged in #1370

**Comment by yarikoptic** [comment]
oh, missed that! ;)
