### ISSUE TITLE
Paths api no longer returning resources

### ISSUE THREAD

**Issue by filippomc** [dandi/dandi-archive#1396]
For instance, a call like https://api.dandiarchive.org/api/dandisets/000147/versions/draft/assets/paths/ used to return all files and folders from the root of the archive, while now it returns only some metadata like 

```json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "path": "sub-P1",
            "version": 565,
            "aggregate_files": 10,
            "aggregate_size": 77665528,
            "asset": null
        }
    ]
}
```

**Comment by pgleeson** [comment]
It would be great to get this resolved, or another API endpoint identified, as currently the listing of DANDI repository contents on OSBv2 is broken, e.g.: https://www.v2.opensourcebrain.org/repositories/58

**Comment by yarikoptic** [comment]
The issue is being looked at, sorry for still breaking the API in our 0.x series of the archive - it is indeed still in flux somewhat.

As a possibly quick and dirty workaround if you would like to get ALL assets (so no folders -- would need to be built by your code), we have also all of them (and for different versions) 

- in endpoint above: https://api.dandiarchive.org/api/dandisets/000147/versions/draft/assets/ 
- exported as .jsonld and .yaml files on S3, see e.g.

```
❯ s3cmd -c ~/.s3cfg-dandi-backup -v ls s3://dandiarchive/dandisets/000003/draft/
2022-01-24 20:24       273343  s3://dandiarchive/dandisets/000003/draft/assets.jsonld
2022-01-24 20:24       278717  s3://dandiarchive/dandisets/000003/draft/assets.yaml
2022-01-24 20:24         5212  s3://dandiarchive/dandisets/000003/draft/collection.jsonld
2022-01-24 20:24         3494  s3://dandiarchive/dandisets/000003/draft/dandiset.jsonld
2022-01-24 20:24         3441  s3://dandiarchive/dandisets/000003/draft/dandiset.yaml
```
but I guess you would want to cache any of those since indeed could be large for some dandisets.

**Comment by pgleeson** [comment]
Thanks for the update @yarikoptic

**Comment by AlmightyYakob** [comment]
>used to return all files and folders from the root of the archive, while now it returns only some metadata

It's returning a hierarchical view of the data, as it would be represented on a filesystem. The response that you saw is what's present at the root level, just the `sub-P1` folder. You're saying, you expect to see a flat listing of all files (no matter the folder depth) from the asset paths endpoint?

That endpoint has returned a hierarchical view of dandiset assets for [over a year](https://github.com/dandi/dandi-archive/commit/ef68e17ee8045778f72f4045aa8b131549a0ba8e) now. Was the original DANDI integration with OSB created some point before then?

**Comment by AlmightyYakob** [comment]
Actually, I was wrong about that. I'm not sure the asset paths endpoint ever returned a flat list of files...

**Comment by satra** [comment]
@AlmightyYakob - you are correct, this is still returning the correct setup. it's just that this particular dataset has a single subject.

@filippomc - so perhaps this hasn't had any regression as such. please let us know what the expectation was.

**Comment by AlmightyYakob** [comment]
@filippomc Is there a remaining issue here?

**Comment by filippomc** [comment]
@AlmightyYakob closing.
