### ISSUE TITLE
Re-evaluate the `VALIDATING` status on the `Version` model

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#1447]
The [`VALIDATING` field](https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/models/version.py#L30) on the `Version` model is currently not used anywhere. We should re-evaluate if we should be using it / if we even need it.

**Comment by satra** [comment]
@mvandenburgh - how is the async task of validation represented? and how is it communicated that the process has finished?

**Comment by waxlamp** [comment]
I believe we decided to remove this; closing in favor of #1653.
