### ISSUE TITLE
Clickable email button when ContactPerson is an organization

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-archive#1461]
There are a couple of dandisets where the designated ContactPerson is an organization, such as [45](https://dandiarchive.org/dandiset/000045?search=ibl&pos=7), [149](https://dandiarchive.org/dandiset/000149?search=ibl&pos=6), and  [409](https://dandiarchive.org/dandiset/000409/draft)

But if I wanted to send an email do that organization through the DANDI interface, I'd probably have to crawl through the metadata yaml to find the email adress

Compared to when that ContactPerson is a 'person', their name shows up in the Contributors section and has a little blue clickable button to get in contact with them, such as in [350](https://dandiarchive.org/dandiset/000350?search=ahrens&pos=1)

**Comment by waxlamp** [comment]
@satra, how do you feel about including organizational Contributors in the contributors list (including an email address if present)?

**Comment by satra** [comment]
organizational contributors are already included in the contributor list and can even be included in citations. the email address part is an optional thing. right now we include email for persons not organizations in the ui. i see no reason to not include it for any entity that has it.

**Comment by CodyCBakerPhD** [comment]
> organizational contributors are already included in the contributor list and can even be included in citations.

Should I report that as a bug then? I have the organization set as both those things but they fail to show as such on the main page

[dandiset 409](https://dandiarchive.org/dandiset/000409?search=ibl&pos=1)

![image](https://user-images.githubusercontent.com/51133164/216646321-26306ed2-205e-4502-8a1b-4995c371fc5f.png)

but

![image](https://user-images.githubusercontent.com/51133164/216646952-81c22ef2-2e9a-4fbd-8a03-0fe16f3313da.png)

**Comment by satra** [comment]
yes, i would file this as a bug, and probably an easy fix.  does it also not show up in citation?

**Comment by CodyCBakerPhD** [comment]
Yeah they do show up in the copy/paste box of 'Cite As'

"International Brain Laboratory (2023) IBL - Brain Wide Map (Version draft) [Data set]. DANDI archive. https://dandiarchive.org/dandiset/000409/draft"

**Comment by marySalvi** [comment]
Appears to have been fixed with #1499
