### ISSUE TITLE
dandisets that fail validation give the date January 24, 2022

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1471]
<img width="272" alt="image" src="https://user-images.githubusercontent.com/844306/217274413-c548e302-012c-48ed-b6be-a9c8990b338a.png">

for the following dandisets:

'000018',
'000021',
'000022',
'000024',
'000028',
'000030',
'000031',
'000032',
'000033',
'000036',
'000038',
'000042',
'000046',
'000047',
'000048',
'000050',
'000051',
'000052',
'000058',
'000060',
'000063',
'000066',
'000068',
'000071',
'000072',
'000105',
'000106',

**Comment by bendichter** [comment]
Maybe this is correct? Did something happen on that date?

**Comment by yarikoptic** [comment]
as for `license` - probably nothing new, @satra clarified in https://github.com/dandi/dandi-cli/issues/1205#issuecomment-1419965170 that those old(er) datasets . I don't see in https://github.com/dandi/dandi-schema/blob/master/CHANGELOG.md when it became required, and I guess that is not really relevant.

**Comment by yarikoptic** [comment]
as for the date -- indeed, from our dataladi'fication we see that timestamp (only) was updated, no other changes:

```
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets/000018$ git log -p HEAD^^..HEAD
commit 414f0f3a93da0afe303d0bfb6953df6ccc63406c (HEAD -> draft, github/draft, github/HEAD)
Author: DANDI User <info@dandiarchive.org>
Date:   Mon Jan 24 15:39:11 2022 +0000

    [backups2datalad] Only some metadata updates

diff --git a/.dandi/assets-state.json b/.dandi/assets-state.json
new file mode 100644
index 0000000..c4da188
--- /dev/null
+++ b/.dandi/assets-state.json
@@ -0,0 +1,3 @@
+{
+    "timestamp": "2022-01-24T15:39:11.016267+00:00"
+}

commit de569244ddf0a026078e2f5191bc666c7910702d
Author: DANDI User <info@dandiarchive.org>
Date:   Thu Jan 20 17:07:49 2022 +0000

    [backups2datalad] Only some metadata updates

diff --git a/dandiset.yaml b/dandiset.yaml
index 22bae8d..b5f1bef 100644
--- a/dandiset.yaml
+++ b/dandiset.yaml
@@ -12,7 +12,7 @@ assetsSummary:
   numberOfBytes: 0
   numberOfFiles: 0
   schemaKey: AssetsSummary
-citation: Tao, Can; Zhang, Guang-Wei (2021) Mouse Spinal Cord Ephys Dataset (Version
+citation: Tao, Can; Zhang, Guang-Wei (2022) Mouse Spinal Cord Ephys Dataset (Version
   draft) [Data set]. DANDI archive. https://dandiarchive.org/dandiset/000018/draft
 contributor:
 - affiliation:
```

**Comment by waxlamp** [comment]
Is this still a problem?

**Comment by bendichter** [comment]
yes

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/844306/221224122-9243d576-3250-4f55-b17d-1bf8768e3ea6.png">

**Comment by AlmightyYakob** [comment]
> there was a dandi-archive release on day prior `# v0.3.12 (Mon Jan 23 2023)`, but I am not sure if time zone of both dates is the same ...

You're a year late! (/s). But yes, there actually _was_ a [release](https://github.com/dandi/dandi-archive/releases/tag/v0.1.38) directly on Jan 24, 2022, however looking at the changes, I don't see anything that touches the dandiset modified field ([changelog](https://github.com/dandi/dandi-archive/compare/v0.1.37...v0.1.38)).

@bendichter / anyone who can, do you have an example from that list of dandisets that are _known_ to have been updated more recently than Jan 24, 2022? Looking at a few of them, they seem to have no files / not been updated in a long time.

**Comment by waxlamp** [comment]
We already are tracking an issue to tighten which changes are able to affect the last updated timestamp (#458). In the case of this issue, I don't think there's anything actionable here _unless_ we are able to detect a change in last updated that did not come from a manual updating action. As such I'm going to close this issue but the discussion (following from AlmightyYakob's question above) can and should continue here.
