### ISSUE TITLE
organization as author

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1472]
In dandiset 149, an attempt was made to list an organization as an author:

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/844306/217279197-08d90d53-acb6-48a6-8cad-cebc7362ca83.png">

This caused a validation error in the metadata. The IBL does like to list "International Brain Laboratory" as an author, e.g. [here](https://www.biorxiv.org/content/10.1101/2022.05.09.491042v3).

If we want to allow this, we should allow it in the schema. If we want to disallow this, we should prevent it in the metadata editor.

**Comment by satra** [comment]
what is the validation error that you received? is it because the url is not wellformed (`https://` missing)?

**Comment by satra** [comment]
did you try adding `https://` for the url?

**Comment by bendichter** [comment]
@satra ok yes, that was the issue. I find that difficult to decipher from the validation error messages from the API and from the Web UI. The web UI says nothing about URL at all. The validation errors start with two errors that are irrelevant. I suppose fixing #1477 would fix this anyway, so I'll close in favor of that issue.
