### ISSUE TITLE
dandiset 32 has no owner

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1484]
[dandiset 32](https://dandiarchive.org/dandiset/000032) has no data and no owners. This appears to be from the early days when we were playing around. It fails metadata validation because it has no contributors and no license. It's also a bit strange to have an ownerless dandiset. What should we do about this?

**Comment by waxlamp** [comment]
I used my admin powers (mwaaa ha haa!) to add you as an owner, @bendichter. To fix the validation errors, you should now be able to add yourself as a contributor and select a license.

I understand you don't actually need for this dandiset to be valid, but it's useful to try out a method of making these "early adopter" dandisets valid.
