### ISSUE TITLE
Could the trailing slash be added to "location" while navigating folders?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1546]
Could trailing slash (or url encoded `%2F`) be added to the `location=` option in URLs while navigating file tree? E.g. instead of https://dandiarchive.org/dandiset/000026/draft/files?location=derivatives%2FEPIC%2Fsub-EXC022 having https://dandiarchive.org/dandiset/000026/draft/files?location=derivatives%2FEPIC%2Fsub-EXC022%2F when getting to that folder?

The rationale: in dandi-cli, to not guess on either we are to deal with an asset or a folder we disambiguate with that trailing `/`. It used to be that Web ui had it and then users could simply cut/paste folder URL from the browser.  Since some time (not noticed when) web UI stopped adding that final `/` and it broke that simple workflow of "cut/paste url into `dandi download`".

Ref: https://github.com/dandi/dandi-cli/issues/1256

**Comment by AlmightyYakob** [comment]
I'll just point out that the `location` parameter always refers to a folder, and can never be used to refer to an asset, so I don't understand the issue you're dealing with. Regardless, it seems that there's also some inconsistencies with trailing slashes in the GUI itself, and if it doesn't break anything downstream, I have no issue always adding a trailing slash.

**Comment by waxlamp** [comment]
ping @yarikoptic

**Comment by yarikoptic** [comment]
ok, we are adjusting dandi-cli code to hardcode the knowledge that `location` in that URL (but not in `dandi://` urls which we also have) could point only to a folder: https://github.com/dandi/dandi-cli/pull/1305. Thank you @AlmightyYakob for pointing that out!  I will leave it up to you either to add the final `/` to exemplify that fact, and to close this issue one way or another.
