### ISSUE TITLE
Output a complete record submitted to datacite in case of failure to mint a DOI

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1550]
It seems that there is some mystery around how/why we got the error from datacite server while minting DOI, which was initially recorded in https://github.com/dandi/dandi-schema/issues/166 

Do we have a complete exact metadata record submitted to datacite anywhere in the logs?  at Sentry level seems to cut it

![image](https://user-images.githubusercontent.com/39889/227979671-66dbe386-468f-42fa-ac54-a3febcccf2f2.png)

so we can't really tell why 

```json
{"errors":[{"source":"funderIdentifier","uid":"10.48324/dandi.000458/0.230317.0039","title":"DOI 10.48324/dandi.000458/0.230317.0039: The attribute 'funderIdentifierType' is required but missing. at line 104, column 0"}]}
```
ie what was the line 104 

@djarecka

**Comment by mvandenburgh** [comment]
Looks like sentry has a default size limit for stack traces https://forum.sentry.io/t/some-stack-traces-are-truncated/7309.

But yes, we do log both the request to datacite (including the metadata record), as well as the response when it fails https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/doi.py#L49-L51
