### ISSUE TITLE
Overwrite of metadata from a separate opened dandiest

### ISSUE THREAD

**Issue by jeromelecoq** [dandi/dandi-archive#1573]
A weird, annoying bug happened to me today with DandiArchive
I was editing the metadata of two dandisets on separate safari windows
https://dandiarchive.org/dandiset/000037
and https://dandiarchive.org/dandiset/000459?pos=2
As I saved on dandiset 000459, it overwrote all the metadata of 00037
Colleen G. notified me and I went back. fortunately she had exported a backup so I refilled in the UI for 0037
given that she had done a good job with metadata, there was a lot to fill in.

**Comment by yarikoptic** [comment]
That's odd, but I guess not entirely impossible.
FWIW "Backup" of dandiset metadata also could be found in dandiset.yaml of those in https://github.com/dandisets, eg https://github.com/dandisets/000037/blob/draft/dandiset.yaml

**Comment by satra** [comment]
the meditor state is probably shared across the windows. also in this particular case `schemaVersion` got autoupdated and access status got modified for 000037 (but because this doesn't affect the db for accessstatus, it's all still open access).

**Comment by waxlamp** [comment]
@jeromelecoq, I'm really sorry about this. I'm glad you were able to restore your correct metadata, even if that took some tedious work to accomplish.

We figured out the buggy mechanism that allowed this to happen and have disabled it (see #1575 if you are curious), so it should not happen again. If you run into any further trouble, please don't hesitate to reach out again.
