### ISSUE TITLE
Meditor Bugs

### ISSUE THREAD

**Issue by jjnesbitt** [dandi/dandi-archive#1574]
We found the following bugs with the meditor:

1. The pop-up dialog for restoring previously unsaved metadata is behind the meditor dialog, and "yes" can be easily clicked, thus causing the metadata to be overwritten, possibly unintentionally.
2. When switching dandiset versions without reloading the DLP, the version used to store the undo/redo transactions for the meditor use whatever version was originally loaded, not the current version. An example of this would be if you loaded the DLP with the most recently published version `0.230408.2207`, and you switched to the draft version and opened the meditor. Until you reloaded the page, all of the transactions will be stored in local storage under the key `<USER>-DANDI:<ID>/0.230408.2207-transactions`
3. It seems the watcher responsible for storing unsaved changes from the meditor is not ever firing, causing the intermediate (unsaved) model to never be stored.

**Comment by waxlamp** [comment]
Is this a dupe of #1576? (That issue has a more specific directive, and seems to include the information in this issue, which is why I consider this one the dupe even though it's older.)

**Comment by jjnesbitt** [comment]
This issue was technically filed before #1576, but that issue has a more thorough description, so I'm happy to close this in favor of that issue.
