### ISSUE TITLE
DANDI-API-DY: dandiapi.analytics.tasks.process_s3_log_file_task

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1618]
seems recent but very persistent

![image](https://github.com/dandi/dandi-archive/assets/39889/64257d38-7570-4978-bb97-49ca546fba1c)

**Comment by danlamanna** [comment]
This isn't a bug imo. An n+1 issue on select statements is often (but not always) a problem, but on update queries it often doesn't make sense to combine similar updates that are touching different rows.
