### ISSUE TITLE
multiple emails being sent on user registration

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#1631]
after the new workflow was released, i'm getting multiple emails from the server announcing registration (4x) and review (4x).

**Comment by waxlamp** [comment]
@satra, can you give me a username or email address that's exhibiting this octuple emailing? For example, I see a GitHub user `ulisespereira` with email address pimuntue@gmail.com, but I have just the two emails (one welcome email sent to the user and cc'ed to admins, and one instructing the admins to review that user).

**Comment by satra** [comment]
it was the one with the user: `jiazeyin`. perhaps it was related to the release process. since then all the new ones have had only one. closing for now.
