### ISSUE TITLE
Modify AWS bucket CORS configuration to allow HEAD requests

### ISSUE THREAD

**Issue by magland** [dandi/dandi-archive#1641]
I am trying to read from DANDI nwb files directly from the browser. I have found that [webnwb](https://github.com/brainsatplay/webnwb) works but I think I could load things with a lot lower latency if I used h5wasm directly.

As seen in the screenshot below, the AWS bucket allows PUT, POST, GET, DELETE, but does not allow HEAD.

If it allowed HEAD, then I would be able to use the createLazyFile method of h5wasm without having to hack the HEAD request. Right now I am using the aborted GET request method from hdf5-io

See:
https://github.com/garrettmflynn/hdf5-io/blob/273f60f08168c0c1dfb001d7a7d3ad05baad4521/src/lazy/lazyFileLRU.ts#L273-L279

Supporting HEAD requests would also solve that problem for hdf5-io.

This is related to this very recent issue: #1640 

![image](https://github.com/dandi/dandi-archive/assets/3679296/747f51b1-7cf8-42fe-b1d1-3ff80cd65373)

**Comment by yarikoptic** [comment]
This should be quite easy to instrument, right @AlmightyYakob @waxlamp ?

**Comment by magland** [comment]
@yarikoptic @waxlamp 

I am bumping this issue because I now have renewed need for it. I have been using an aborted get request instead of a proper HEAD request in Neurosift as a workaround to this issue. But now I am having an issue with getting the authenticated redirect URL for an ambargoed dandiset, and I really need to do a HEAD request. Any chance this can be added to the CORS config?

**Comment by waxlamp** [comment]
Hey @magland! Yes, I will work on this today. Sorry for the delay.

**Comment by waxlamp** [comment]
@magland, it seems that this has been done already, though I am skeptical since you're reporting it's not working on your end. But here's an example of me issuing a HEAD request from the command line (in verbose mode so you can see the HEAD request itself, as well as the response):

```
$ curl --verbose --head https://dandiarchive.s3.amazonaws.com/blobs/700/bf7/700bf7b2-363c-48d0-9355-2fb4c0ac2522

*   Trying 52.219.228.252:443...
* Connected to dandiarchive.s3.amazonaws.com (52.219.228.252) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=*.s3.amazonaws.com
*  start date: Apr 22 00:00:00 2024 GMT
*  expire date: Apr  7 23:59:59 2025 GMT
*  subjectAltName: host "dandiarchive.s3.amazonaws.com" matched cert's "*.s3.amazonaws.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
> HEAD /blobs/700/bf7/700bf7b2-363c-48d0-9355-2fb4c0ac2522 HTTP/1.1
> Host: dandiarchive.s3.amazonaws.com
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< x-amz-id-2: QXroKfHnBdMRYpa48a0Aco52gYjsN7DYRwzITJiSvXSM5vyAUGWgkGLU6RkGLoE0xzwfrt0bjNc=
x-amz-id-2: QXroKfHnBdMRYpa48a0Aco52gYjsN7DYRwzITJiSvXSM5vyAUGWgkGLU6RkGLoE0xzwfrt0bjNc=
< x-amz-request-id: 5XE4GM1HWGNETGGB
x-amz-request-id: 5XE4GM1HWGNETGGB
< Date: Wed, 14 Aug 2024 13:54:01 GMT
Date: Wed, 14 Aug 2024 13:54:01 GMT
< Last-Modified: Thu, 08 Aug 2024 15:50:32 GMT
Last-Modified: Thu, 08 Aug 2024 15:50:32 GMT
< ETag: "d0d0f5c1cc531f174646bd6b47174d72-200"
ETag: "d0d0f5c1cc531f174646bd6b47174d72-200"
< x-amz-server-side-encryption: AES256
x-amz-server-side-encryption: AES256
< x-amz-version-id: b6OjmKyzEcdcWdou_8Es0E2ulWgoVibF
x-amz-version-id: b6OjmKyzEcdcWdou_8Es0E2ulWgoVibF
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Content-Type: application/octet-stream
Content-Type: application/octet-stream
< Server: AmazonS3
Server: AmazonS3
< Content-Length: 13366368472
Content-Length: 13366368472

<
* Connection #0 to host dandiarchive.s3.amazonaws.com left intact
```

If this doesn't reflect your experience, can you provide some detail on what's going wrong?

**Comment by magland** [comment]
Ah yes, it is working. There was a bug on my end and I incorrectly thought it was a S3 config issue. You can close this now.

Thanks so much!

**Comment by waxlamp** [comment]
Fixed in https://github.com/dandi/dandi-infrastructure/pull/124.
