### ISSUE TITLE
[Feature Request]: Add 'Questions' button to redirect to issues page of dandiset

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-archive#1643]
I think the current policy if people have questions about a DANDI set is to try to have them ask it on the GitHub issues for the copy of that particular DANDI set

E.g., if I have a question about DANDI set `000350` then I go to https://github.com/dandisets/000350/issues and post an issue there, which will hopefully automatically ping the right people to answer the question

This process would be more obvious if there was a button on each page of the archive, when I'm looking at the main page of a DANDI set. Maybe called 'Ask a question' or something like that, and it directs them to the issues page when they press it. Or perhaps GitHub 'discussions' might be a better format for that? Either way.

@yarikoptic Do you know if it's possible, when the dandisets on https://github.com/dandisets are created, if the GitHub API would allow automatically setting the owners of the DANDI set so have a 'watch' status set on it so that they automatically get notified of questions?

**Comment by yarikoptic** [comment]
ATM users of the dandi archive might not even know that there are github repositories associated with them.
"Ask a question" could indeed me "Open an issue labeled with `question` label" . Adding a label I believe might not be possible via URL to open an issue but we could have `dandisets/` organization wide action based on https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues to do that based on some marker in the issue title/text which would be formed from some template.



> @yarikoptic Do you know if it's possible, when the dandisets on https://github.com/dandisets are created, if the GitHub API would allow automatically setting the owners of the DANDI set so have a 'watch' status set on it so that they automatically get notified of questions?

it should be possible AFAIK.  This and anything related -- let's formalize in https://github.com/dandi/dandi-archive/pull/1595 . I think we could add a section there "Changes on dandi-archive Web UI" outlining what buttons we want to add (e.g., have a web ui Section with buttons: "See issues", "File an issue", "Ask a question" or alike)

**Comment by CodyCBakerPhD** [comment]
Incorporated into #1595
