### ISSUE TITLE
user registered and no github account linked

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1644]
There is a follow up email from @satra on 30 Jun 2023 on that matter.  The email mentioned in the registration approval page is `@gmail.com` whenever I see some logged interactions from `.edu` account.  May be user changed email interim registration/approval process and that somehow broke correspondence?  github api for that user shows .edu email and 

```
  "created_at": "2017-03-06T22:31:33Z",
  "updated_at": "2023-07-01T11:28:05Z"

```

In DB I see two accounts for the name -- one with `@gmail.com` (PENDING, that is where we lack association with github account) and another one with `.edu` - APPROVED and joined 2 minutes after the prior one.

@xmival00 , do you remember any detail from you registering on dandi
- did you switch your email in your github account shortly after after registering at DANDI archive website?
- did you request registration twice?

**Comment by waxlamp** [comment]
Thanks for the background info, @xmival00.

@yarikoptic, I will remove the pending gmail.com application from the system as suggested.
