### ISSUE TITLE
pass to getExternalServices extra info/link to provide "context"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1648]
relates to integration with external services like being added in https://github.com/dandi/dandi-archive/pull/1647/files .

ATM for getExternalServices we are passing only the `url` to the asset and no further information about what that URL for.  I think it would be great if it was possible to provide external service with the context, e.g.

- `origin_page_url` -- url to the page from where we are going to that external service, i.e. that file browser where user came from like https://dandiarchive.org/dandiset/000574/draft/files?location=sub-01
- `origin_dandiset_id` -- dandiset, e.g. `000574`
- `origin_path` --  e.g. `sub-01/sub-01_ses-20161214T171300_behavior+ecephys.nwb`
- `s3_url` -- since most of the time there is no need for content disposition filename etc, so services could just use direct s3 url directly without jumps

Then external service would be able to provide some handful banner / text on what users are working on there and possibly provide back link to the dandiset etc.

**Comment by yarikoptic** [comment]
it seems that according to https://github.com/flatironinstitute/neurosift/issues/40#issuecomment-1631200171 the need is more dire that I thought (attn @CodyCBakerPhD) to enable another ongoing development.  I didn't check the code paths but I would suspect that it should be quite a trivial change. @waxlamp - what would be availability of your team to look at this? or should we consider proposing a PR?

**Comment by satra** [comment]
@mvandenburgh - is there a way to specify which url to use for an asset in the template for an external service (e.g., a blob url or an asset url) ? that itself will get external services a lot of info, and we can think about which parameters perhaps a little longer.

**Comment by mvandenburgh** [comment]
> @mvandenburgh - is there a way to specify which url to use for an asset in the template for an external service (e.g., a blob url or an asset url) ? that itself will get external services a lot of info, and we can think about which parameters perhaps a little longer.

Currently there is not; the web app just supplies the `url` field returned from the asset paths endpoint (which is the S3 blob URL). If there is a need to differentiate between the two, maybe we need to rethink how the external services list is populated, since the original mechanism wasn't designed with this in mind.

**Comment by satra** [comment]
this PR #1655 should address our current issue i think, by simply providing an extra parameter, which a service is welcome to ignore, but it would be good to consider a more robust solution for this (more like what is the data model that can be proposed)

**Comment by waxlamp** [comment]
I believe #1706 fulfills this issue. We can open new issues if the "external service API" needs to be modified further.
