### ISSUE TITLE
Return some kind of info from API top-level

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#166]
See original discussion in #119. The problem is that the top level returns 404, when it could provide something useful.

**Comment by yarikoptic** [comment]
Even https://api.dandiarchive.org/api/ returns 404 which is very suboptimal - it is the top level entry point and it should not 404 but rather provide a record which would inform about what to expect from API server underneath, possibly point to swagger, etc.

**Comment by waxlamp** [comment]
Closing as a dupe of #320.
