### ISSUE TITLE
request: optional link to github repo for discussion and issues

### ISSUE THREAD

**Issue by magland** [dandi/dandi-archive#1705]
I think it would be great to allow a dandiset to link to an external site (e.g., github repo) specific to that dandiset where users can submit issues or initiate discussions.

I realize you could put a link in the description, but I don't think it belongs there.

Perhaps there could be a prominent button to the effect of "SUBMIT ISSUES ABOUT THIS DANDISET HERE".

**Comment by magland** [comment]
Seems to be related to https://github.com/dandi/dandi-archive/pull/1595

**Comment by yarikoptic** [comment]
"Great minds think alike!" ;) so indeed this issue IMHO is a duplicate of 
- https://github.com/dandi/dandi-archive/issues/863
design doc for which is being formalized in the 
- https://github.com/dandi/dandi-archive/pull/1595
you reference
