### ISSUE TITLE
file browser not sorting the contents

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#1740]
i don’t see sub-I58 here (https://dandiarchive.org/dandiset/000026/draft/files?location=)

but i can see it directly: https://dandiarchive.org/dandiset/000026/draft/files?location=sub-I58/ses-Hip-CT/micr&page=1

this is because the results are not sorted and it shows up on the second page.

**Comment by satra** [comment]
it's on the second page, but the results are not sorted and thus unintuitive to follow.

**Comment by waxlamp** [comment]
Closing in favor of #1839 which offers comprehensive details about the bug.
