### ISSUE TITLE
Migrate to pydantic 2.0

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1791]
Should be tested against WiP
- dandi-schema: https://github.com/dandi/dandi-schema/pull/203 
  - web front end which consumes jsonschema export should validate against the new exported schema.
- cli: https://github.com/dandi/dandi-cli/pull/1381

**Comment by waxlamp** [comment]
What is needed for this--to upgrade dandi-archive's dependency on dandi-schema? Is this different from #1820 and #1823?

**Comment by yarikoptic** [comment]
indeed, let's consider this one replaced by #1820 which should be addressed by #1823 for which we are waiting on a frontend expert to check failing test-e2e  (and other possible related untested in frontend tests changes due to changes in jsonschema)
