### ISSUE TITLE
dandi-cli tests broke over new years

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1804]
new years might be coincidental or not

![image](https://github.com/dandi/dandi-archive/assets/39889/5cb88350-ef6f-471b-9199-d0adfce82193)

tests fail with smth like

```
  -                      'endDate': ANY_AWARE_DATETIME_STR,
  -                      'id': AnyFullmatch('urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'),
  +                      'endDate': '2024-01-02 19:17:46.524965+00:00',
  +                      'id': 'urn:uuid:e88064fe-46e7-4244-870e-655615a71595',
                         'name': 'Metadata extraction from DOI',
                         'schemaKey': 'Activity',
  -                      'startDate': ANY_AWARE_DATETIME_STR,
  +                      'startDate': '2024-01-02 19:17:46.440907+00:00',
```

any immediate ideas @dandi/archive-maintainers @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic https://github.com/dandi/dandi-cli/pull/1385

**Comment by mvandenburgh** [comment]
This is still occurring on `dandi-archive` PRs due to https://github.com/dandi/dandi-cli/pull/1385 not being included in a release yet.

**Comment by yarikoptic** [comment]
was released, reran and it passed https://github.com/dandi/dandi-archive/actions/runs/7451758163
