### ISSUE TITLE
odd casing for WWW-Authenticate in 401 response

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1824]
Trying to access embargoed asset without providing authentication credentials in the header results in 401 which should (and is) accompanied with `WWW-Authenticate` header but that one cased oddly as Www-Authenticate.  I do not think we should be "special" here even if casing does not matter:

```shell
❯ wget -S 'https://api.dandiarchive.org/api/dandisets/000403/versions/draft/assets/0cb481e5-b979-4eed-8ea4-9cd0d78276a3/download/' 2>&1 | grep Auth
  Www-Authenticate: Bearer realm="api"
```

but insofar I failed to find where it is coming from so could not propose a PR. on my local drive only following hits

```
❯ recollq-p Www-Authenticate | xargs grep Www-Authenticate 2>/dev/null
/home/yoh/proj/misc/selenium/java/test/org/openqa/selenium/grid/security/BasicAuthenticationFilterTest.java:    assertThat(res.getHeader("Www-Authenticate")).startsWith("Basic ");
/home/yoh/proj/misc/selenium/java/test/org/openqa/selenium/grid/security/BasicAuthenticationFilterTest.java:    assertThat(res.getHeader("Www-Authenticate")).contains("Basic ");
/home/yoh/proj/misc/helpme/helpme/main/workers/tasks.py:    not_asking_auth = "Www-Authenticate" not in response.headers
/home/yoh/proj/misc/helpme/helpme/main/workers/tasks.py:    challenge = response.headers["Www-Authenticate"]
/home/yoh/proj/misc/localstack/localstack/services/stepfunctions/asl/component/state/state_execution/state_task/service/state_task_service_api_gateway.py:        "Www-Authenticate",
```

and I figured out how to do case sensitive search on github but apparently way too many hits! https://github.com/search?q=%2F%28%3F-i%29Www-Authenticate%2F+&type=code

anyone knows? @dandi/archive-maintainers @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic Why is this a problem?  HTTP headers are case-insensitive.  Any tool that breaks on `Www-*` but not `WWW-*` is buggy.

**Comment by yarikoptic** [comment]
it is not a problem per se, but also we do not case it as WwW or wWW etc.  It is just odd looking to see acronym (WWW) to be cased like that and apparently (from that github and local search) it might be feasible that some code is indeed buggy to assume this specific casing.  Thus I think it would be better to have it `WWW-Authenticate` as listed e.g. on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate .

I can see an argument though that "it is all consistently cased across all header fields as Word-Casing" -- I like consistency, but consistent incorrect casing of acronyms making it look odd. Hence asking if we could/should make it  `WWW-Authenticate`.

**Comment by waxlamp** [comment]
I believe DRF (which is generating this header) must be consistently applying Camel-Kebab-Case to every header name, regardless of whether it might be pedantically more correct for it to be `WWW-Authenticate`.

I'm closing this as wontfix for a few reasons which all harmonize:
- as John points out, this just doesn't matter
- there is a case to be made for blind consistency resulting in `Www-Authenticate`
- if this were a bug, it would need to be fixed upstream in DRF (and not in this repository)
