### ISSUE TITLE
"403 : Forbidden" error when trying to access from UK. Have tried different computers, logins and IP adresses

### ISSUE THREAD

**Issue by NilsNyberg** [dandi/dandi-archive#1841]
Hey. As the title says, I have tried to access hub.dandiarchive.org from many computers, github logins and IP addresses throughout London and I always get the same error. Can dandiarchives not be accessed from the UK?

**Comment by yarikoptic** [comment]
have not received similar reports insofar. AFAIK  we do not impose any restrictions.  Only hub or main dandiarchive.org is also an issue?  how does it manifest?

**Comment by yarikoptic** [comment]
approved now -- should work now.

So the error message was already informative if read/cited in full ;) I don't think there is anything more we could/should do.

**Comment by NilsNyberg** [comment]
Yes thank you, I assumed it had been approved without checking
