### ISSUE TITLE
Add "ass-covering" usage agreement?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#1880]
openneuro got one recently

![image](https://github.com/dandi/dandi-archive/assets/39889/d64c6c65-93e9-4f81-90bf-ef7fa96e9b19)

**Comment by waxlamp** [comment]
This is not something we can do directly. We need advice from lawyers on this type of thing. Further, I believe we can cover this through #536 which directly addresses terms and conditions for using DANDI.
