### ISSUE TITLE
in-browser AVI viewing broken

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1908]
e.g. for this link: https://api.dandiarchive.org/api/assets/69041b8f-0da7-4785-845f-721129099b9a/download/?content_disposition=inline

which is found here: https://dandiarchive.org/dandiset/000559/draft/files?location=sub-1528%2Fsub-1528_ses-reinforcement-031eb0c7-128f-4e57-9fe3-94680b8129f6_behavior%2Bimage%2Bogen&page=1

the viewer just looks like this:

<img width="408" alt="image" src="https://github.com/dandi/dandi-archive/assets/844306/5a54b7cd-b768-415c-a5ca-038c2449d2dd">

**Comment by waxlamp** [comment]
Hey Ben, thanks for this issue report.

I'm not sure exactly why the video player is broken, though I suspect it's that the video is not encoded in a way that the browser can decode with its built-in codecs.

But I did download the whole video file, only to discover that it's 30 seconds of blank frames with no audio track. Furthermore, it seems to be supplying every frame explicitly (the whole video consists of the same (blank) video frame, repeated), causing a big file size to encode (literally) nothing.

Did something maybe go wrong during acquisition of the data or preparation of this video?

**Comment by bendichter** [comment]
@pauladkisson do you know what might be going on here?

**Comment by pauladkisson** [comment]
> I'm not sure exactly why the video player is broken, though I suspect it's that the video is not encoded in a way that the browser can decode with its built-in codecs.

This doesn't surprise me. I was unable to play the videos appropriately with video player applications, but it read fine using cv2.

> But I did download the whole video file, only to discover that it's 30 seconds of blank frames with no audio track. Furthermore, it seems to be supplying every frame explicitly (the whole video consists of the same (blank) video frame, repeated), causing a big file size to encode (literally) nothing.

This is strange though...I'll download it myself and take a look.

**Comment by pauladkisson** [comment]
Ok, I double checked and this file is fine -- looks like a normal depth video from this dataset (use code below to read it yourself).

```python
import cv2

raw_video = cv2.VideoCapture('path/to/0abe7609-af66-4d81-865e-a20a4b414908_external_file_0.avi')

while True:
    # Read a frame from the video
    ret, frame = raw_video.read()

    # If the frame is not read successfully, the video has ended
    if not ret:
        break

    frame = frame / frame.max() # Normalize the frame

    # Display the frame in a window
    cv2.imshow('Frame', frame)

    # Wait for a key press to exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

# Release the video capture and close the window
raw_video.release()
cv2.destroyAllWindows()
```

**Comment by bendichter** [comment]
Yes, @magland has a solution for this already, where you can submit a job to translate the movie to mp4 so it can be streamed.

**Comment by magland** [comment]
> Yes, @magland has a solution for this already, where you can submit a job to translate the movie to mp4 so it can be streamed.

Note that this simple PR has not yet been merged: https://github.com/dandi/dandi-archive/pull/1983

Once that's merged you will be able to open AVI in neurosift directly from DANDI
