### ISSUE TITLE
Paginating over 000876 assets returns duplicate entries

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-archive#1914]
As of 2024-04-01 09:13 -05:00, running the following code:

```python
import requests

DANDISET = "000876"

with requests.Session() as s:
    url = (
        f"https://api.dandiarchive.org/api/dandisets/{DANDISET}/versions/draft/assets/"
    )
    while url is not None:
        data = s.get(url).json()
        for asset in data["results"]:
            print(asset["path"])
        url = data["next"]
```

produces https://gist.github.com/jwodder/e68a10a9a93ed4e44ace26df671cfc6e as output (among other possibilities; see #1915).  Running `sort $FILE | uniq -d` on this file lists 2001 paths that occur more than once: https://gist.github.com/jwodder/dd462ce668ea59167f031a7acbcd2abe.

**Comment by jjnesbitt** [comment]
Fixed via #1910
