### ISSUE TITLE
webUI pagination error

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1925]
I'm pretty sure this was working previously but navigating through pages of Dandisets on the WebUI has a strange bug where if you look past the first page it only shows a single page available on the bottom.

https://github.com/dandi/dandi-archive/assets/844306/d769a862-4639-45ba-b40e-da884b80c8fb

**Comment by yarikoptic** [comment]
yikes, confirming!  yet another good candidate for automated e2e testing!

**Comment by satra** [comment]
duplicate of #1917
