### ISSUE TITLE
Add a tooltip to describe the steps to logout from dandiarchive.org

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-archive#1935]
## Description

Thank you @aaronkanzer and @waxlamp for the previous discussion on this topic.

(This issue can only be resolved once #1934 is resolved.)

A user must log out of both dandiarchive.org and github.com to be fully logged out of dandiarchive.org.  That is if a user logs out of dandiarchive.org and then selects `LOGIN WITH GITHUB` on dandiarchive.org they do not need to enter credentials, because they are still logged in to github.com.  Would like to make it clear to users that one must log out of both accounts to be fully logged out of dandiarchive.org.

## Possible solution

Would suggest adding a tooltip to the user interface to describe that logging out of github.com is a required step to be fully logged out.

**Comment by waxlamp** [comment]
I don't think this is true--I believe I have a solution to #1934 that does not require logging out of GitHub (which would not be an acceptable solution in any case; requiring people to log out of a code hosting service just to clear login info for a data archive is bad UX).

I will close this issue for now while I escalate #1934; if we need to reopen this, we can (I will consider you, @kabilar, as the person who will do this if and when needed, if that's ok with you).
