### ISSUE TITLE
bug: error when trying to save metadata

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1961]
<img width="1725" alt="image" src="https://github.com/dandi/dandi-archive/assets/844306/89f5c984-0771-4ca5-a77d-52a128170bcb">

https://dandiarchive.org/dandiset/001038

I was signed in and I am an owner of this Dandiset. I did a lot of clicking in and out of the modal window to reference other material. That may have done it.

**Comment by waxlamp** [comment]
Do you remember if you remained logged in after the error occurred? Perhaps you happened to refresh the page as well?

**Comment by bendichter** [comment]
Sorry, this was a while ago and I'm not really sure what caused this or how to reproduce it.

**Comment by waxlamp** [comment]
I'm going to close this since we can't repro, but of course if it happens again please revive this thread (or just file a new issue).
