### ISSUE TITLE
Unable to disassociate GitHub account

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#1966]
https://github.com/dandi/dandi-archive/assets/844306/f3445b9b-672a-4419-b77a-21ce76b219cd

I used my girlfriend's GitHub account so I could walk myself through the account approval process, but now I am now able to sign out of that account and back into my main account. As you can see, I am signed into my normal GitHub account on the GitHub website. I have tried restarting my entire computer. Is there any way to get my account back? I'd really rather not delete all my cookies.

**Comment by kabilar** [comment]
Hi @bendichter, I think this is related to #1934 but I'm not sure what a temporary work around would be.

**Comment by bendichter** [comment]
@kabilar thanks for directing me to this. I will delete this issue.
