### ISSUE TITLE
Allow for Zarr uploads to embargoed Dandisets

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-archive#1982]
Related discussions:
- [Embargo Redesign design doc](https://github.com/dandi/dandi-archive/blob/master/doc/design/embargo-redesign.md)
- https://github.com/dandi/dandi-archive/issues/1745

**Comment by kabilar** [comment]
Hi @CarolineMagnain, thanks for reaching out.  Currently this feature is not available.  We will be working to engineer the backend components that are required to enable this feature and will update this thread as progress is being made.  Thanks.

**Comment by jjnesbitt** [comment]
This is a feature that's next on the roadmap, as the main blocker of re-implementing embargo has been finished. I will begin work on this in the near future.

**Comment by CarolineMagnain** [comment]
Thanks a lot

**Comment by jjnesbitt** [comment]
Closed via #2069

**Comment by kabilar** [comment]
Hi @jjnesbitt, thanks for your quick work on this issue.  Perhaps we should keep this issue open until we have tested in staging, built integration tests with the DANDI Client, and pushed to production?

**Comment by kabilar** [comment]
Depends on https://github.com/dandi/dandi-cli/pull/1540
