### ISSUE TITLE
Zarrbargo design document

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#2003]
As it has been on our on our list of targets and we agreed that it is orthogonal (at least largely), it would be great to hear your current ideas on how it could/should be implemented.  I think a design document PR would be great to see what you are thinking about.

**Comment by aaronkanzer** [comment]
@jjnesbitt @waxlamp 

Here is a rough draft Design Doc that @kabilar and I used for our initial first pass at using AWS Cloudfront presigned cookies as a method of fast access to zarr assets in S3

• https://github.com/lincbrain/linc-archive/pull/111/files

Here is also our main PR that included the API endpoint that issued the cookies to the user
• https://github.com/lincbrain/linc-archive/pull/126/files

Let me know if you'd like to take a first pass at the design doc, meet prior, or have me take a peek -- happy to work with whatever your preference might be.

Cc @yarikoptic @satra

**Comment by yarikoptic** [comment]
just a note: I think such a document among tech details should describe the need , or provision refactoring to remove the need for [EmbargoedZarrArchive](https://github.com/dandi/dandi-archive/blob/master/dandiapi/zarr/models.py) which survived the 
- https://github.com/dandi/dandi-archive/commit/9fc81a44a6d9d7a4831bbfb1c5e21b92be230684 : "Rip out embargoed models"

I feel that like for `AssetBlob` it should be sufficient to just define `embargoed` bool attribute as long as we keep embargoed zarrs in the same bucket/location as public zarrs.

**Comment by jjnesbitt** [comment]
Superseded by https://github.com/dandi/dandi-archive/pull/2069.

"Zarrbargo" is really just the extension of the embargo re-design to include zarrs, which doesn't really entail a large overarching change. That PR description contains all the information that would be present in a design doc.
