### ISSUE TITLE
Error message when navigating to embargoed Dandiset

### ISSUE THREAD

**Issue by kabilar** [dandi/dandi-archive#2020]
Hi team, the following message gets displayed when I navigate to a Dandiset that is embargoed (and for which I am not an owner).

![image](https://github.com/user-attachments/assets/6a9601e1-78a9-425c-81cd-2b742638f4f4)

Instead of the error message, perhaps we could display a splash screen that says the Dandiset is currently embargoed?

Thank you.

**Comment by satra** [comment]
closing in favor of #1350

**Comment by kabilar** [comment]
Thanks.  Sorry, didn't see that issue.
