### ISSUE TITLE
Harmonize (pre-commit) formatting of frontend (vue) code

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#2101]
ATM ruff-format is used for the backend code (in dandi-cli we use black). But frontend vue code is full of individual preferences. 

https://prettier.io/docs/en/precommit.html describes possible setups for pre-commit. 

- https://github.com/dandi/dandi-archive/pull/2100 shows how prettier would modify current codebase

**Comment by waxlamp** [comment]
Closing in favor of #2110
