### ISSUE TITLE
Document Swagger log in process

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#233]

**Comment by yarikoptic** [comment]
what is "Swagger log in process"?  is issue still pertinent @waxlamp @AlmightyYakob ?

**Comment by AlmightyYakob** [comment]
I think he meant "login", as in, how to login to the swagger page. However, he might have filed this issue before we had the "Django Login" button, which is now present on the swagger page. This button takes you to our login page, which redirects to github, and really doesn't require any more explanation imo. I think we can close this.
