### ISSUE TITLE
Add release CI step to check the tag format

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#388]
The release should fail early if the tag is not of the form `v1.2.3`.

**Comment by yarikoptic** [comment]
ideally add a check that this particular `release` is a newer release than the one which is already deployed, e.g. by comparing to version from the `/info` end-point but #222 needs to be fixed first.

**Comment by mvandenburgh** [comment]
This is superseded by #968, since the near future `auto` will handle tagging releases for us.
