### ISSUE TITLE
timestamps should incorporate time zone info

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#432]
various places require timestamps (datePublished, publishedBy, and others). since we will eventually get to different instances of the api running potentially in different time zones, it would be good to incorporate timezone info into timestamps.

**Comment by danlamanna** [comment]
I did some cursory digging and as far as I can tell we're storing and displaying ISO8601 timestamps with timezones everywhere except for versions and assets that were published prior to #492 being merged. In both of these cases our timestamps are UTC without explicitly denoting that fact, so we *could* backfill it if we wanted to.

**Comment by satra** [comment]
thanks @danlamanna - in that case we may want to make such updates.

i would say the major part of this issue seems to have been addressed.
