### ISSUE TITLE
Enable Deep Glacier backup

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#524]
There are Terraform modules we should use to set this up.

**Comment by yarikoptic** [comment]
FWIW there is also https://github.com/dandi/dandi-infrastructure/issues/99  

@waxlamp -- my paranoia kicked in again.  What could be an ETA for enabling glacier backup of out main production bucket?

**Comment by waxlamp** [comment]
I've added this to the current sprint, so I'll take a look at it ASAP.

**Comment by satra** [comment]
@waxlamp - please do provide a cost estimate before we trigger.

**Comment by waxlamp** [comment]
> @waxlamp - please do provide a cost estimate before we trigger.

Roger that.

**Comment by waxlamp** [comment]
> @waxlamp - please do provide a cost estimate before we trigger.

Roger that.

**Comment by yarikoptic** [comment]
@waxlamp please prioritize this issue! FYI, although we have some adhoc backups of regular assets, our coverage of zarr content in backup is very small, so I think that the time is "very right" to get proper backup up.

**Comment by waxlamp** [comment]
Let's meet to discuss this in detail. I more and more don't think it's just a matter of enabling Glacier. Glacier is not really a backup solution, it's much more to do with object lifecycle management. I'd like to meet to discuss what the actual problem is (i.e., are we afraid of logic errors permanently deleting things that should not be deleted? Or are we actually trying to save money by cycling long-unused items into cheaper storage? Or a third option?).

Do you mind setting something up?

**Comment by yarikoptic** [comment]
We can indeed talk about life cycle etc (I will continue on slack for that), but that would be a "bigger fish to fry". ATM I feel we need to have at least this "ass cover" to ensure that we do not loose data while we come up with some better long term solution/object lifecycle management.

**Comment by waxlamp** [comment]
I think the best answer here is to use delete markers, rather than try to roll our own backup solution. Or else, we need to find out what AWS's actual "backup solution" is. But delete markers would give us plenty of "ass cover" right?

**Comment by yarikoptic** [comment]
We use delete markers, but we also have scripts which kill delete markers and all prior versions e.g. upon user request or as a part of GC (we do not want to grow history indefinitely)... such scripts/actions could be buggy (what code isn't?) leading to e.g. excessive deletion etc.  So indeed S3 versioning gives some "ass cover" but still leaves opportunity for a wind to blow it away.

**Comment by waxlamp** [comment]
Let's still meet. I don't think it's obvious that the answer here is "enable deep glacier".

**Comment by yarikoptic** [comment]
IIRC the verdict was "enable simplest glacier policy for now to get a backup and think about more 'optimal' later", or am I misremembering?

**Comment by yarikoptic** [comment]
ping @waxlamp . The topic of glacier backup keeps coming up for years and I thought that we agreed on a "simplest way forward" for now, or am I misremembering?

**Comment by waxlamp** [comment]
I've asked @mvandenburgh to look into it now.

**Comment by kabilar** [comment]
cc @aaronkanzer

**Comment by waxlamp** [comment]
This issue is quite stale. We originally thought that "enabling deep glacier" would at a stroke solve our backup problem. After looking into it more deeply, we realized that solving our "backup problem" required quite a different approach. In general, I believe this issue was also aimed at our garbage collection issues, so I'm going to close this in favor of issues/PRs like https://github.com/dandi/dandi-infrastructure/pull/157 and https://github.com/dandi/dandi-archive/issues/177.
