### ISSUE TITLE
Monitor draft manifest writing task performance

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#530]
The task which writes draft manifest files to S3 currently writes every dandiset every night. Since most dandisets will not be changed every day, we should optimize to only write draft dandisets that were modified in the last 24 hours.

This involves testing that the draft version modification date is updated correctly when dandiset metadata is change and when assets are modified or added to the dandiset.

**Comment by danlamanna** [comment]
Once #458 is done and we have a solid grasp on the update lifecycle of a dandiset version, we can migrate manifest writing to be on demand instead of a cron job.

**Comment by waxlamp** [comment]
Closing this because the performance issue has been resolved. We're tracking problems with timestamps in other issues.
