### ISSUE TITLE
Endpoints that return collections not 404'ing for nonexistent Dandisets

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-archive#559]
Given an ID for a Dandiset that doesn't exist — say, 123456 — making a request to an API endpoint of that Dandiset that returns a collection of objects will return an empty collection instead of 404'ing.  This affects the following endpoints:

* https://api.dandiarchive.org/api/dandisets/123456/versions/
* https://api.dandiarchive.org/api/dandisets/123456/versions/draft/assets/
* https://api.dandiarchive.org/api/dandisets/123456/versions/draft/assets/paths/

https://api.dandiarchive.org/api/dandisets/123456/users/ returns a 404, though.

Similar behavior occurs when the Dandiset exists but the version does not (as long as the version ID is in a valid format, though; invalid IDs always result in a 404); examples:

* https://api.dandiarchive.org/api/dandisets/000003/versions/0.999999.9999/assets/
* https://api.dandiarchive.org/api/dandisets/000003/versions/0.999999.9999/assets/paths/

**Comment by yarikoptic** [comment]
@waxlamp please close if it was addressed

**Comment by AlmightyYakob** [comment]
I believe this has been fixed.
