### ISSUE TITLE
Detect "gaps" in dandiset ID increment

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#627]
Between [72](https://gui.dandiarchive.org/#/dandiset/000072) and [105](https://gui.dandiarchive.org/#/dandiset/000105) and again between [173](https://gui.dandiarchive.org/#/dandiset/000173) and [206](https://gui.dandiarchive.org/#/dandiset/000206), the intervening dandiset IDs are "missing" (i.e., no record of any dandisets created with those IDs). In both cases, the interval is 23, which seems like is not a coincidence.

We need a way to probe whether something is causing the DB's "next dandiset" increment value to change inappropriately.

**Comment by yarikoptic** [comment]
FWIW, our "datalad"ification script had been run quite regularly in the past days. In that script we do not remove deleted datasets, so if at some point any dataset between 173 and 206 was created we would have likely created one.  But nope -- we have no datasets between those two.

**Comment by yarikoptic** [comment]
Although does not "fit" the consistency of having 206, since we do allow admins to create dandisets with a specific identifier -- may be some admin level dandi folk created 000206 for someone with that specific identifier? (relates to #61 ;-) )

**Comment by yarikoptic** [comment]
for clarity: are we relying on django's auto id increment (which I think what it is) or do we have some logic at any level?
curious: if we create, delete, and again create a dandiset -- will both have the same id? (as an `id` of the first one was "put back in the pool" when deleting)

**Comment by dchiquito** [comment]
We use Django's default ID fields, which use a postgres sequence to autoincrement.

One possibility is that an admin uploaded a dandiset with an identifier already specified; we still have that feature that allows admins to upload to a specific dandiset for migration purposes.

**Comment by mvandenburgh** [comment]
For completeness - we discussed this further on slack and agreed to add a check to the dandiset creation endpoint that logs an error if a new dandiset's identifier is incorrect.

**Comment by yarikoptic** [comment]
AFAIK it was not resolved right? no other clues of any kind came up?

**Comment by waxlamp** [comment]
> AFAIK it was not resolved right? no other clues of any kind came up?

No other clues came up, but AFAIK the problem has not recurred. If it happens again we can re-open this, but I closed it because I don't believe it's a problem at the current moment.

**Comment by yarikoptic** [comment]
> AFAIK the problem has not recurred.

what made you think so? 

https://dandiarchive.org/dandiset?page=1&sortOption=1&sortDir=-1&showDrafts=true&showEmpty=false shows now 000337 and next one 000301 . Looked at django:

![image](https://user-images.githubusercontent.com/39889/191303964-63dba163-b34d-4a63-8662-13085f0239c7.png)

so even the very last ones seems to be sequential -- just a few weeks back we had a huge gap, unless it was created/removed. So I checked the heroku logs I have -- no sign of 000303 ever created
```
(dandisets) dandi@drogon:/mnt/backup/dandi/heroku-logs/dandi-api$ grep 'Created dandiset 000302' 202209*log 
20220902-2001.log:2022-09-03T00:50:42.707747+00:00 app[web.1]: [00:50:42] INFO     Created dandiset 000302 given request with   dandiset.py:300
^C
(dandisets) dandi@drogon:/mnt/backup/dandi/heroku-logs/dandi-api$ grep 'Created dandiset 000303' 202209*log 
(dandisets) dandi@drogon:/mnt/backup/dandi/heroku-logs/dandi-api$ 
```

so IMHO issue persists.

**Comment by yarikoptic** [comment]
> One possibility is that an admin uploaded a dandiset with an identifier already specified; we still have that feature that allows admins to upload to a specific dandiset for migration purposes.

@dchiquito had this good idea! @waxlamp could you please check logs where you have access (papertrail) on how 000335 came to life?  I have gaps in my logs collection (heroku interface "disconnects" and require me to relogin manually) so I might have missed that since the very first mentioning I have is 

```
20220912-0912.log:2022-09-12T13:10:28.175128+00:00 heroku[router]: at=info method=GET path="/api/dandisets/000335/versions/draft/" host=api.dandiarchive.org request_id=aacd8a40-8d81-44dc-abbf-cadd35f01d83 fwd="SENSORED" dyno=web.1 connect=0ms service=7ms status=200 bytes=1407 protocol=https
20220912-0912.log:2022-09-12T13:10:28.178396+00:00 app[web.1]: 10.SENSORED - - [12/Sep/2022:13:10:28 +0000] "GET /api/dandisets/000335/versions/draft/ HTTP/1.1" 200 1018 "-" "backups2datalad (https://github.com/dandi/dandisets) httpx/0.22.0 CPython/3.8.13"
```
(from our backuping server) so as if it already existed

**Comment by AlmightyYakob** [comment]
> One possibility is that an admin uploaded a dandiset with an identifier already specified; we still have that feature that allows admins to upload to a specific dandiset for migration purposes.

I did a test, and observed the following:

1. When specifying an identifier for dandiset creation, the auto-increment field does **not** jump up to that newly specified ID. Normal creation afterwards will go back to where it was last auto-incremented.
2. When the auto-increment _does_ reach an identifier that was already manually specified, the creation will fail with a duplicate key error, which we can account for. After that, it will continue on past that identifier as normal.

**Comment by yarikoptic** [comment]
we do create/delete in programmable fashion on staging but not on the main instance.

do you have access to logs for at least 1 month?  swagger or API -- there should be logs upon creation of the dandiset if someone explicitly requested for it to be created.  [As I showed before](https://github.com/dandi/dandi-archive/issues/627#issuecomment-1252561817), I could not find any entry for creation between those dandiset ids, but my logs coverage has gaps so it is not 100% proof (e.g. I do not see record for [000335](https://dandiarchive.org/dandiset/000335) which was created):

```
(base) dandi@drogon:/mnt/backup/dandi/heroku-logs/dandi-api$ grep 'Created dandiset 0003\(0[23456789]\|2[0-9]\|3[012345678]\)' 202209*log  | uniq
20220902-2001.log:2022-09-03T00:50:42.707747+00:00 app[web.1]: [00:50:42] INFO     Created dandiset 000302 given request with   dandiset.py:300
20220915-1501.log:2022-09-15T19:12:49.111295+00:00 app[web.1]: [19:12:49] INFO     Created dandiset 000336 given request with   dandiset.py:304
20220918-0101.log:2022-09-18T05:53:58.957205+00:00 app[web.1]: [05:53:58] INFO     Created dandiset 000337 given request with   dandiset.py:304
20220918-0201.log:2022-09-18T05:53:58.957205+00:00 app[web.1]: [05:53:58] INFO     Created dandiset 000337 given request with   dandiset.py:304
20220924-0701.log:2022-09-24T11:52:04.501585+00:00 app[web.1]: [11:52:04] INFO     Created dandiset 000338 given request with   dandiset.py:304
```

if you have access to papertrail for the last month - can you see if there was any "Created dandiset 0000303"??

**Comment by waxlamp** [comment]
No `000303` in the logs... they jump straight from `000302` to `000335`.

I wonder if your create/delete script might have accidentally run on production in this (and the previous) instance. If that script works by directly creating model instances (rather than going through the API) it might have left no trace, as it were.

**Comment by yarikoptic** [comment]
BTW -- wild idea, since we are talking about scripts. django DB schema upgrade scripts -- is running though leaves some log entry which could let us detect if there was their execution e.g. in `000302 - 000335` gap?  I might then be able to check some prior dates.

**Comment by waxlamp** [comment]
> BTW -- wild idea, since we are talking about scripts. django DB schema upgrade scripts -- is running though leaves some log entry which could let us detect if there was their execution e.g. in `000302 - 000335` gap? I might then be able to check some prior dates.

Can you clarify what you mean? I'm not following.

**Comment by satra** [comment]
seems to have happened again.

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/184063/220147178-4fce5d98-f5b4-4ddb-9315-ae1fc9af928b.png">

**Comment by waxlamp** [comment]
I'm consulting with the KW team on how we can best collect extra data about what might be happening here.

**Comment by waxlamp** [comment]
I think this mystery is solved: https://help.heroku.com/PRNW4R5Z/why-are-there-gaps-in-my-postgres-id-sequence.

It is also common to see 32 numbers in the sequence skipped: https://www.cybertec-postgresql.com/en/gaps-in-sequences-postgresql/.

In this context, if you google around a bit you'll see that this is a design tradeoff between eliminating performance cliffs from write contention and being able to have a gapless ID sequence, with the former concern winning the hearts and minds of DB engineers everywhere. This is almost certainly what is happening to us--a Kitware colleague's honest advice was to eliminate the idea of gaplessness from our mental model of how Postgres ID sequences work.

I am going to close this issue as completed since we have a proper explanation for what's happening. If there are any remaining issues to discuss, we can carry on here or open a new issue.
