### ISSUE TITLE
Modify search and listing endpoints to protect embargoed dandisets

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#632]
Embargoed dandisets should only be visible to their owners, and to admins.

[design doc](https://github.com/dandi/dandi-api/blob/96c85ca5b3c1932b450cb00d4c375f0a176e2261/doc/design/embargo-mvp.md?plain=1#L19)

**Comment by dchiquito** [comment]
This is done, but this is also a very important part of embargo, so someone should do some QA in staging and look for any spots I might have missed.

**Comment by waxlamp** [comment]
@mvandenburgh could you do the requested QA in staging?

**Comment by mvandenburgh** [comment]
I tested these out in staging and couldn't find anything wrong with them, looks like they're working as intended.
