### ISSUE TITLE
Find a better way to do DandisetViewSet queryset filtering

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#670]
I think the `user=me` solution is reasonable, I was aiming the TODO at the way `get_queryset` was using the request method/query parameters to do filtering. It seems a little questionable to me, but I have yet to find a better way to do it.

_Originally posted by @dchiquito in https://github.com/dandi/dandi-api/issues/583#issuecomment-1004921469_

```
def get_queryset(self):
        # Only include embargoed dandisets which belong to the current user
        queryset = Dandiset.objects.visible_to(self.request.user).order_by('created')
        if self.action == 'list':
            # TODO: This will filter the dandisets list if there is a query parameter user=me.
            # This is not a great solution but it is needed for the My Dandisets page.
            ...
```

**Comment by waxlamp** [comment]
@dchiquito, when you get a chance can you clarify what is questionable about the current code?

**Comment by dchiquito** [comment]
My personal vibe is that the switch statement thing we're doing with `if self.action == 'list': ...` isn't very nice. It means that we're doing all sorts of method specific filtering in a specific method, which involves using query parameters defined in far away methods and using them here. It feels like spaghetti and I don't like it much.

However, my current understanding is that this how it's done in DRF.

**Comment by waxlamp** [comment]
> However, my current understanding is that this how it's done in DRF.

I think this means we should close the issue (your red flag notwithstanding)?

**Comment by dchiquito** [comment]
> we should close the issue

Either that or phone a friend and ask for a second opinion. I'm fine with either.

**Comment by waxlamp** [comment]
Maybe @brianhelba can do a drive-by. Otherwise, if you want to ask on Slack that would be good. I'll leave it to you to close this issue or take other appropriate action as needed.

**Comment by danlamanna** [comment]
I think long term the plan should be to move more logic into a layer away from large class based viewsets, but there's nothing specifically actionable here IMO - closing.
