### ISSUE TITLE
Implement unembargoing

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#679]
See [design doc](https://github.com/dandi/dandi-api/pull/619) ([old link](https://github.com/dandi/dandi-api/blob/96c85ca5b3c1932b450cb00d4c375f0a176e2261/doc/design/embargo-mvp.md?plain=1#L103-L121)):
> * New endpoint: `POST /api/dandisets/{dandiset_id}/unembargo`
>
>  Unembargo an embargoed dandiset.
>
>  Only permitted for owners and admins. If the `embargo_status` is `OPEN` or `UNEMBARGOING`, return 400.
>
>  Set the `embargo_status` to `UNEMBARGOING`, then dispatch the unembargo task.
>
>* Unembargo task
>
>  For every `Asset` with an `EmbargoedAssetBlob` in the dandiset, convert the `EmbargoedAssetBlob` into an `AssetBlob` by moving the data from the embargo bucket to the public bucket.
>  These could be >5GB, so the [multipart copy API](https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjectsMPUapi.html) must be used.
>  The ETag and checksum must remain undisturbed; the only change should be where the data is stored.
>  Verify that the resulting unembargoed assets match one-for-one (in the database) with the embargoed assets that were copied.
>  Once finished, the `access` metadata field on the dandiset will be updated to `OpenAccess` and `embargo_status` is set to `OPEN`.
>
>  Before copying data, check if an existing `AssetBlob` with the same checksum has been uploaded already (this would have happened after uploading the embargoed data).
>  If so, use it instead of copying the `EmbargoedAssetBlob` data.

**Comment by waxlamp** [comment]
I thought we were using "unembargo" in place of "release"?

**Comment by dchiquito** [comment]
Weird, that's what it says in the [PR](https://github.com/dandi/dandi-api/pull/619/files) but when went into the commit history and grabbed the most recent content it still said "release". I'll fix it

**Comment by AlmightyYakob** [comment]
> For every Asset with an EmbargoedAssetBlob in the dandiset, convert the EmbargoedAssetBlob into an AssetBlob by moving the data from the embargo bucket to the public bucket.

Does this include all versions? Or is it the latest published version, the draft version?

> Once finished, the access metadata field on the dandiset will be updated to OpenAccess and embargo_status is set to OPEN.

A Dandiset doesn't contain a `metadata` field, but a `Version` does. To which versions should this operation be applied? I suspect this will depend on the first question.

**Comment by dchiquito** [comment]
Embargoed dandisets are not publishable, so embargoed dandisets are 1-to-1 with draft versions. You only need to consider the draft version for unembargo, so "dandiset metadata" refers to the dandiset's draft version metadata (apologies for the imprecision).

**Comment by satra** [comment]
@dchiquito - just wanted to make a note here that while we will not want to revert unembargoing, we will likely want the possibility of a future draft being embargoed. 

- create an embargoed dataset
- unembargo
- publish (with embargo the draft option)

the last option when checked would allow new additions in embargoed mode to the dandiset while keeping the published version public. this would support use cases like adding new data to existing dandisets, but using all of the data for analyses, etc.,.

this option can be implemented later, but wanted to bring it up as it may not be a huge lift.

**Comment by dchiquito** [comment]
I don't think it would be hard to do at all, since embargoed dandisets are allowed to contain unembargoed data.
@satra can you add that to https://github.com/dandi/dandi-archive/blob/master/doc/design/embargo-full.md?
