### ISSUE TITLE
Prevent all asset modifications while unembargoing

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#692]
Unembargoing involves copying all of the assets in a dandiset from the embargo bucket to the public bucket, so naturally we want to freeze any asset changes while that is happening. Specifically,

* You may not create new assets attached to an unembargoing dandiset
* You may not update an asset attached to an unembargoing dandiset
* You may not delete an asset attached to an unembargoing dandiset
* You may not initialize an upload of a blob to an unembargoing dandiset

**Comment by jjnesbitt** [comment]
Closed via #1957
