### ISSUE TITLE
Add link to dandi jupyterhub onto main page or dandiset page

### ISSUE THREAD

**Issue by rly** [dandi/dandi-archive#697]
In our NWB outreach, we sometimes use or refer to the dandi jupyterhub, but as far as I can see, there is no link or easy way to get to the dandihub except if you happen to know the URL. Can this link be added to the main page and/or from a dandiset page? I vaguely remember this existing previously.

**Comment by waxlamp** [comment]
@satra, should this go on the front page?

**Comment by satra** [comment]
it should go on the header somewhere, so people can click on it from any page i think.
