### ISSUE TITLE
allow admins to manage owners

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#699]
currently ownership management is limited to owners. admins should be allowed to modify ownership. i can do the modification using the API, so it would be useful to have that option on the UI (similar to publish).

**Comment by mvandenburgh** [comment]
The current solution doesn't display any warnings if an admin modifies the owners of a dandiset they don't own - I'll reopen this issue and implement a warning dialog.

**Comment by waxlamp** [comment]
Closing with remaining work tracked in #858.
