### ISSUE TITLE
a few (missing) pieces in new DLP

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#707]
- [ ] in this issue dandi/dandiarchive#876 we made sure that funding information was given additional preference, and if not present it showed as "No funding information available". this was to gently remind users that they weren't putting funding contributions in. the section that displays funding, it should be displayed with "No funding information available". https://github.com/dandi/dandi-archive/pull/817

- [x] also associated projects is now missing. that section should be at the bottom of the DLP.  https://github.com/dandi/dandi-archive/pull/818

- [x] assets summary doesn't collapse into row mode on a small display, unlike related resources and funding information. https://github.com/dandi/dandi-archive/pull/819

for the future, since it is hard to compare DLP completeness before and after on staging, we should craft a staging dandiset that has as much metadata/metadata variation as possible.

**Comment by mvandenburgh** [comment]
This is still waiting on #817.
