### ISSUE TITLE
update copyright and "cut a release"?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#709]
ATM we have at the bottom of the page

© 2021 DANDI
version 0.1.0-923-g35c5e3a

With the New Year and a new DLP deployed, I think it would make perfect sense to boost version and update copyright. WDYT?

**Comment by yarikoptic** [comment]
I think it was done since then.

**Comment by waxlamp** [comment]
I approved this PR some time ago, and left it for your final review and merge (and perhaps release): https://github.com/dandi/dandi-archive/pull/893

**Comment by yarikoptic** [comment]
oh right -- forgot about that one and it was not even referenced here.  updated that PR with my current preference of having actual years. I will keep this issue closed since we have plenty of open ones ;)
