### ISSUE TITLE
Add "replace=UUID" option to POST /dandisets/{version__dandiset__pk}/versions/{version__version}/assets/ 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#71]
To facilitate atomic (handled on the server with needed precautiouns, e.g. not removing UUID asset from dandiset until all needed checks passed) replacement of an asset for a path.  Follow up to #65 and complimentary to #70 (we need DELETE anyways).

Why to specify UUID?  to informatively resolve "race" whenever two clients start uploading for the same PATH, then one finishes and replaces original UUID, and then 2nd one arrives to the same point: if just a `bool` it would happily replace it instead of IMHO a more correct behavior -- an error that "asset {UUID} is not associated with the {PATH}. Could happen if asset was recently replaced".

**Comment by dchiquit** [comment]
I don't understand the use case for this feature. What are you trying to achieve that can't be achieved by `PUT /dandisets/{version__dandiset__pk}/versions/{version__version}/assets/{uuid}/`?

Perhaps it isn't clear, but the UUID is random will be preserved by `PUT` operations. Say there is already an asset that exists at `GET /dandisets/000001/versions/draft/assets/12345678-1234-1234-1234-1234567890ab/`. If you wanted to upload new data to that asset, you would follow the upload flow, at which point you would have a validated `sha256`. Call `PUT /dandisets/000001/versions/draft/assets/12345678-1234-1234-1234-1234567890ab/` with `{"path": old_path, "metadata": old_metadata, "sha256": new_sha256}`, and the asset will be updated atomically.

**Comment by yarikoptic** [comment]
> I don't understand the use case for this feature.

imagine you and me (or me from one computer and me from another, by mistake pointing in both cases to the same file) are uploading the same file (asset for a path) at the same time.  The slowest one would "win" and neither of us would know that there was any "competition"... but I guess the main confusion is in :

> Perhaps it isn't clear, but the UUID is random will be preserved by PUT operations. 

That is not how it was intended originally and may be that is why there is dichotomy in our thinking ;-) IIRC (@satra and @mgrauer could correct me if I am wrong) the plan was: an asset record for a UUID is **never** updated. A new asset (UUID) should be minted for any call which modifies/provides new metadata/file.  This way we indeed loose "association"/"history" for an asset changes, but that is "by design". The reason/purpose, to guarantee that asset ID unambigously identifies the state of an asset (along with version of metadata etc).  If nothing in asset for UUID changes, "publish" for a version would just take those UUIDs as is, and would have no need to create new copies for each and every one of the 1000s of files which might be in a release (didn't check what is done now) to guarantee that released version has exactly that version of metadata etc.

Looking at "Planning meeting for dandiarchive API roadmap" google doc ATM relevant calls:
```
/dandisets/:identifier/versions/:version/assets [POST] 
 ← create an asset (or a copy) by providing :upload_id (from /uploads[POST]) or :asset_id  
 → {new :asset_id} + out-of-band validation of the correct upload
```
although in case of 
```
/dandisets/:identifier/versions/:version/assets/:asset_id [PUT,PATCH] 
← update metadata and/or finalize upload if :upload_url 
→ <metadata> (“lock on the path”) (some fields, like checksum/digests, contentSize, will not be allowed to be changed)
```
it seems to not mention "metadata includes new :asset_id".

If asset UUID can mutate (file, metadata) and be different across versions of the dandiset, it means that it is (dandiset_id, version, asset_UUID) triplet needed to identify the asset and its metadata (then why do we bother with UUIDs? could have been just an index ;)). It would also mean that we would not be able to (later) reuse the same asset across dandisets (we plan to provide such functionality) since if anything in its record would change - it would effect it in multiple datasets.

**Comment by satra** [comment]
just chiming in on a few things here from the original design:
1. assets do not have versions they are unique. 
2. we need to be able to say an asset belongs to multiple dandisets (a many to one mapping from dandisets).
3. we explicitly removed isPartOf from asset metadata to make it stand alone better.

to track changes in an asset, we can log the provenance during the transaction of a `PUT/POST`.

also, i know the api is undergoing changes, but i just wanted to get it out there that the `GET` request on either dandiset or asset should return only the contents of the metadata field as the record. this means that the `identifier` field in the metadata, `version` for dandiset, and `url` field needs to be updated by the server, but also other fields that are computed on the server side. i would be fine with it returning an additional `database id` if that's helpful for us to track things.

perhaps we can touch base early next week to discuss.

**Comment by waxlamp** [comment]
@yarikoptic what is the status of this issue? If it is still a valid issue, could you update the issue description with a detailed example of the problem you're trying to solve?

**Comment by waxlamp** [comment]
@yarikoptic ^^^

**Comment by yarikoptic** [comment]
FWIW, at least updating metadata (PUT on the  for an existing asset did produce a new asset and it became used in the tree

![image](https://github.com/dandi/dandi-archive/assets/39889/104e616c-29cb-4b8d-a966-f02629bf985a)

so at least that is good. Original post was about POST to `/assets/` endpoint which is to create new assets... but trying to create an asset with an existing already at that path asset resulted in error

![image](https://github.com/dandi/dandi-archive/assets/39889/239c0436-139f-4555-b194-6d507d1d22d3)

so it seems that hypothetical race condition I was worrying about can no longer happen so let's just let this issue RiP
