### ISSUE TITLE
Update AIBS dandisets' license fields

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#711]
_Originally posted by @satra in https://github.com/dandi/dandiarchive/issues/858#issuecomment-1002669465_:

> we need to fix their published dandiset records (they gave us permission), but they changed all their licenses to CC-BY

**Comment by waxlamp** [comment]
This is done. See:
- https://gui.dandiarchive.org/#/dandiset/000023
- https://gui.dandiarchive.org/#/dandiset/000109

**Comment by satra** [comment]
the metadata records on s3 were not adjusted. for example see:

https://dandiarchive.s3.amazonaws.com/dandisets/000023/0.210914.1900/dandiset.yaml

**Comment by satra** [comment]
also the draft dandiset was not adjusted.

**Comment by waxlamp** [comment]
> also the draft dandiset was not adjusted.

These are now adjusted. Looking into the S3 metadata file.

**Comment by waxlamp** [comment]
@satra, the s3 metdata records should now be updated. Take a look and let me know if everything looks ok.

**Comment by satra** [comment]
thank you @waxlamp - looks good.

**Comment by satra** [comment]
the final thing we may need to update is the doi record. will have to check how to do that.
