### ISSUE TITLE
Update DLP to display embargoed dandisets properly

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#715]
Add UI for displaying embargo state and for unembargoing ("releasing").

[design doc](https://github.com/dandi/dandi-api/blob/96c85ca5b3c1932b450cb00d4c375f0a176e2261/doc/design/embargo-mvp.md?plain=1#L14-L17)

**Comment by mvandenburgh** [comment]
Closed by https://github.com/dandi/dandiarchive-legacy/pull/1021
