### ISSUE TITLE
add "Sort by:" Version

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#734]
I wanted to look at published dandisets.  One way for that is to sort by version so that published ones would precede the draft ones.  An alternative/complimentary is faceted search but that would be larger undertaking.

As a companion to dandi/dandiarchive#943 this issue possibly amplifies the need to RF UI to make "sorting column" ("Modified", "Identifier", "Name") not having a dedicated button but rather to be the drop down to select from. And then "order" could be the next button.  That would allow for nearly arbitrarily large selection of what to sort by.

**Comment by djarecka** [comment]
I've started working on this, but I realized that this is done under the cogwheel icon

**Comment by waxlamp** [comment]
@yarikoptic, are you happy with calling this issue closed by the "show drafts" toggle we have now?

**Comment by yarikoptic** [comment]
yes, seems to work very nicely, thank you! (apparently we have about 7 pages worth of empty dandisets on main instance)
