### ISSUE TITLE
add context viewer support for other file types

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#742]
- json
- csv
- tsv
- png
- jpg/jpeg
- ome.tiff (although this may be complicated given their sizes)

**Comment by yarikoptic** [comment]
Users are asking for the feature! ;)

**Comment by yarikoptic** [comment]
We already do that for some video files IIRC, so we should do also for all of these -- just let browser to show them.

**Comment by yarikoptic** [comment]
shouldn't it be patch for the https://github.com/dandi/dandi-archive/blob/1ce8a9174a14baf82ea98f71624058be8424112c/dandiapi/api/views/asset.py#L173C16-L173C28 to add `text/` and `image/` ?

**Comment by yarikoptic** [comment]
hold on -- we already have "Open in Browser" and it works!  should we just close this?

**Comment by yarikoptic** [comment]
I would vote to open, but feel free to reopen if more to be done
