### ISSUE TITLE
Support HEAD requests to `/zarr/{zarr_id}.zarr/{path}`

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-archive#746]
It would be nice if dandi-api responded to HEAD requests to `/zarr/{zarr_id}.zarr/{path}` with a redirect to an S3 URL suitable for performing a second HEAD request.  Currently, making a HEAD request to `/zarr/{zarr_id}.zarr/{path}` results in "405 Method Not Allowed", and making a GET request to the endpoint returns a redirect to an S3 URL whose signature makes it only valid for GET requests.  Being able to make a HEAD request in this way would simplify retrieving the size & "last modified" date of a file in a Zarr asset.

**Comment by dchiquito** [comment]
As discussed in #674, the root problem this issue addresses may be resolved by #802

**Comment by jwodder** [comment]
@dchiquito No, the "root problem" for this issue is the difficulty of getting the size and "last modified" timestamp of a file in a Zarr.  Checksums are a separate issue.

**Comment by dchiquito** [comment]
OK, my understanding was that that information was needed to determine when data had been modified, which can also be done with a checksum. I will do this ASAP

**Comment by jwodder** [comment]
@dchiquito For the record, the download code uses all three data points (size, mtime, and digest/checksum) when deciding whether to download over a local file, with the exact logic depending on the value of the `--existing` option.  For "overwrite-different", size is used for a quick preliminary check, followed by checking the digest if the local & remote sizes are the same.  Mtime is used for the "refresh" option, which also means that the mtime needs to be set on the local file after downloading.
