### ISSUE TITLE
medium size menu layout

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#759]
The layout looks great when large and when small, but there's an awkward middle ground:

![image](https://user-images.githubusercontent.com/844306/124321194-487b4380-db4b-11eb-8748-622e01d022fd.png)

* the logo is tiny
* the "new dandiset" and user initials are stacked awkwardly

**Comment by yarikoptic** [comment]
should this issue be transferred to `dandiarchive`?

**Comment by waxlamp** [comment]
> should this issue be transferred to `dandiarchive`?

Nope, it's in the right place now (`dandiarchive` is now `dandiarchive-legacy`, and archived).

**Comment by waxlamp** [comment]
Has been fixed.
