### ISSUE TITLE
metadata viewer: Make URLs into <A>

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#762]
https://gui.dandiarchive.org/#/dandiset/000055/draft

![image](https://user-images.githubusercontent.com/39889/124043597-5741e900-d9d9-11eb-8375-39de586012be.png)

URL of the resource is not a link as it should be (with all security related additions like opening in new window/tab etc)

**Comment by waxlamp** [comment]
This is now done.
