### ISSUE TITLE
Reordering contributors is very clunky

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandi-archive#766]
This applies to any list of sufficiently large objects. VJSF renders the whole object in the list, although that's really not necessary. VJSF has [slots](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#slots) which can be used to extend functionality, although I'm not sure if our exact issue can be addressed this way. More investigation needs to be done.

**Comment by mvandenburgh** [comment]
Resolved by redesigned meditor in #862
