### ISSUE TITLE
"login" brings user to the https://gui.dandiarchive.org/#/

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#767]
If I am already in a dandiset (e.g. https://gui.dandiarchive.org/#/dandiset/000029), and click logout -- all good, I stay in the same page.

If I try to re-login again then two things happen and possibly related thus filing together
- I get forwarded to "Authorize DANDI GUI?" https://api.dandiarchive.org/oauth/authorize/?redirect_uri=https%3A%2F%2Fgui.dandiarchive.org%2F&client_id=...  URL (so `redirect_uri` does not carry dandiset any longer), even though I did authorize github before (so I expect that to not happen again or for a while)
- and when I click authorize I get to the top landing page

**Comment by waxlamp** [comment]
This is a very minor UX thing. I'm going to close as unplanned. If it becomes important, we can re-open this or refile an issue with appropriate context information.
