### ISSUE TITLE
Require license selection at dandiset creation time

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#778]
a license is a required element of every dandiset. can we add license selection when someone creates a dandiset (at present we are only allowing cc0 and ccby. the license types should be pulled in from dandi schema.

**Comment by yarikoptic** [comment]
related issue: https://github.com/dandi/dandischema/issues/115 in which I argue *against* license selection for embargoed dandisets, and have that selection at Unemabrgo point.

**Comment by mvandenburgh** [comment]
This was completed in #839.
