### ISSUE TITLE
Very large dandisets

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#78]
We may be seeing dandisets with potentially millions of files. We should consider how the system will behave with that many rows in the DB.

**Comment by waxlamp** [comment]
As part of this investigation, let's either locate a dataset with millions of files, or create a dummy dandiset of our own that has thousands, or tens of thousands, or millions of files in it.

**Comment by satra** [comment]
let's also consider a deployment where we can try these things independent of the production server.

**Comment by waxlamp** [comment]
> let's also consider a deployment where we can try these things independent of the production server.

Good idea. We have the basic pieces to accomplish this, but we'll plan to tackle this in more depth after the Django API is more solidly in place.

**Comment by yarikoptic** [comment]
I will produce/push a dummy soon with let's say 1 mil of files to see what would happen

**Comment by waxlamp** [comment]
@yarikoptic, @dchiquito: what's the status of this issue? I propose we either perform the experiment (upload a 1 million file dandiset), capture any issues that result, and then close this issue, or close this issue without doing that.

**Comment by danlamanna** [comment]
Closing this for now since it seems too ill defined. If we later upload large datasets and run into problems we can open specific issues.

**Comment by yarikoptic** [comment]
FWIW 000026 is the largest one ATM AFAIK and some timings could be gathered from https://github.com/dandi/dandi-api-webshots where that dandiset is the *winner* across all timings eg. says it takes 6 seconds to list the files
