### ISSUE TITLE
Add owners of each dandisets as contributors

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#788]
This is a one-time fix operation that depends on dandi/dandiarchive#425 being solved first.

The fix should, for each dandiset, add any owners as contributors if they are not already present in the contributor list.

**Comment by yarikoptic** [comment]
didn't we have this issue resolved?

**Comment by waxlamp** [comment]
Indeed we do: https://github.com/dandi/dandi-archive/blob/7d1805f76d296b0d80e00c929c2e4fd0893fe887/dandiapi/api/views/dandiset.py#L247-L256
