### ISSUE TITLE
Design a new release process for unified repo

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandi-archive#796]
Instead of a `master`-following `staging` branch that deploys the frontend to staging, and a manual release procedure that promotes the backend from staging to production, etc., we should have a single process for both.

The process will be something like: merging to `master` causes both the backend and frontend to deploy to staging; a manual release will cause both to deploy to production.

**Comment by waxlamp** [comment]
@mvandenburgh, I'd like to knock this out sooner rather than later, if you have the bandwidth for it. Can we meet to discuss a strategy?

**Comment by mvandenburgh** [comment]
Just dumping my thoughts on this that I had written down from when I looked into it a little while ago, we can discuss further when we meet in person -

The backend Heroku deployment should largely stay the same, while the frontend Netlify deployment method will change entirely.

Currently, we are using Netlify's Github integration to react to a push to `master` by deploying to production (i.e. a "pull-based" approach). We'll want to change this to a "push-based" approach, where *we* tell Netlify to deploy to staging on push to `master` and deploy to production on release. There seems to be a GH action that does this in a similar way to the heroku deploy action we use https://github.com/marketplace/actions/netlify-deploy. Alternatively, Netlify has a CLI that does this too.
