### ISSUE TITLE
Zarr checksum recalculator tool

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#806]
> s3 checksums information duplication: good that `upload or delete` handle necessary checks for consistency etc, but that is IMHO the point of `fsck` to check if state remains consistent whenever it is expected that it should or must be consistent. So, we might need to add such checks later on, while may be any code working with those checksums and having access to both checksums could check if they are consistent and alert user (who can alert us) that something is odd.  E.g., although unlikely, AFAIK mismatch could potentially happen in a race condition between "read" and "write" operations for a .zarr if we allow for zarr to mutate in place.

_Originally posted by @yarikoptic in https://github.com/dandi/dandi-archive/issues/674#issuecomment-1013435052_

**Comment by waxlamp** [comment]
I'm not really sure what's being requested here. An `fsck` type management script?

**Comment by yarikoptic** [comment]
> An `fsck` type management script?

yes, to ensure that each zarr content tree on S3 has consistent with it checksums "tree"

**Comment by dchiquito** [comment]
We are going to need this tool (or a subset of it) to compute checksums on zarrs that were uploaded directly to S3.
