### ISSUE TITLE
Server needs to be updated for schema 0.6.2

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-archive#814]
Currently, using the latest release of the CLI (v0.34.1), trying to upload to either production or staging fails with:

```
dandi.exceptions.SchemaVersionError: Server requires schema version 0.6.0; client only supports 0.6.2.  You may need to upgrade dandi and/or dandischema.
```

Despite what the message says, it is the servers that need to be upgraded.

**Comment by dchiquito** [comment]
To resolve things in production I set `DJANGO_DANDI_SCHEMA_VERSION` to `0.6.2` in the production heroku instance. That should be removed as soon as this is released to production.

I will also set that in staging. Staging should be fixed permanently as soon as #815 is merged.
