### ISSUE TITLE
assets not validating properly

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#825]
see the validation errors on this dandiset: https://dandiarchive.org/dandiset/000037/draft

```python
 {'status': 'Invalid',
  'validation_errors': [{'field': '',
    'message': 'Metadata version 0.6.2 is not allowed. Allowed are: 0.6.0, 0.4.4, 0.5.1, 0.5.2.'}],
  'id': '9127f9c3-1bd8-4cca-8310-646e4f2d8335'}]

In [41]: url = f"https://api.dandiarchive.org/api/dandisets/000037/versions/draft/assets/{valid[-1]['id']}"

In [42]: req = requests.get(url, headers={"Accept-Header": "application/json"})

In [43]: meta = req.json()

In [44]: validate(meta, json_validation=True)
```

it's possible this and others got caught in the period when the library wasn't updated on the server.

**Comment by satra** [comment]
also https://dandiarchive.org/dandiset/000217/draft (which was created today). seems like the server/validation task is running an older version of dandischema.

**Comment by waxlamp** [comment]
I imagine this has been fixed since then... reopen if there's still a problem here.
