### ISSUE TITLE
Make embargo endpoints return 401/403 instead of 404

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#827]
Right now embargo endpoints are set up to return 404s, acting as if the embargoed dandiset does not exist, if the client is not authorized to see the embargoed data. As discussed in https://github.com/dandi/dandi-cli/issues/867 we should return 401 if the client is unauthorized and 403 if the client does not have permission.

**Comment by jwodder** [comment]
Duplicate of #669?

**Comment by dchiquito** [comment]
It is indeed a duplicate
