### ISSUE TITLE
feat request: redirect https://dandiarchive.org/dandiset/7 to https://dandiarchive.org/dandiset/000007

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#829]

**Comment by satra** [comment]
we used to have this feature, but @yarikoptic said we should stop doing this. this is more of a policy thing at one level, but also as we remove the redirector it may be a practical question as well as to how.

**Comment by bendichter** [comment]
Let me explain why I'd like this.

For the NWB ecosystem paper, I have a table of users to illustrate how widely adopted NWB is that looks like this:

![image](https://user-images.githubusercontent.com/844306/150408353-0cb0b5fc-401a-491b-b1ab-6892cf39afef.png)

Then I have at the bottom:
> All DANDI datasets can be found at https://dandiarchive.org/dandiset/{id}

which isn't quite true, and I don't know how to easily communicate this. I guess I could change the text to:

> All DANDI datasets can be found at https://dandiarchive.org/dandiset/{6-digit-zero-padded-id} e.g. https://dandiarchive.org/dandiset/000007

**Comment by satra** [comment]
one way would be turn those numbers into links.

**Comment by bendichter** [comment]
I suppose, but do supplemental materials usually allow links where the link destination and link label are different?

**Comment by satra** [comment]
they should. i would be worried about an outlet that didn't.

**Comment by waxlamp** [comment]
I see the practical need for you, @bendichter, but I think I agree with the general sentiment that we shouldn't do this. It's hard for me to express why I feel that way. What was @yarikoptic's original argument?

**Comment by yarikoptic** [comment]
```shell
$> python3 -c 'import this' | head -n 4 | tail -n 1
Explicit is better than implicit.
```

those are our dandiset IDs, and should be treated as a complete "thing" (i.e. a string), not just some numeric number formatted to some specific length with 0s.   For one, we could outgrow the largest number and then logic would need to be "adjusted" if casting/formatting is to happen.  There might be more argumentation if you follow https://github.com/dandi/redirector/pull/39 which is what @satra had in mind.  And situation would have been different if from the beginning we had agreed that "dandiset ID is an integer", so we did have `/7` and then `/000007` would have been illegal.

So, even though I feel the desire/need here, overall I would really prefer to be "explicit" and "precise" even if at the cost of some sugaring.  If needed -- situation should/could be clarified in text where special casing like this is desired

> Then I have at the bottom:
> 
> > All DANDI datasets can be found at [https://dandiarchive.org/dandiset/{id}](https://dandiarchive.org/dandiset/%7Bid%7D)
> 
> which isn't quite true, and I don't know how to easily communicate this. I guess I could change the text to:
> 
> > All DANDI datasets can be found at [https://dandiarchive.org/dandiset/{6-digit-zero-padded-id}](https://dandiarchive.org/dandiset/%7B6-digit-zero-padded-id%7D) e.g. https://dandiarchive.org/dandiset/000007

all human beings should love and know python, so you can say `https://dandiarchive.org/dandiset/{id:06d}` ;)

**Comment by bendichter** [comment]
OK, I changed them to links

**Comment by waxlamp** [comment]
Thanks, @yarikoptic, for the argument, and thanks, @bendichter, for your flexibility.
