### ISSUE TITLE
Add some visual indicator/marker for embargoed dandisets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#833]
Went to https://gui-staging.dandiarchive.org/#/dandiset to find some embargoed dataset to "check out".  I am logged in as a mighty myself so I can see the dataset titled "Embargoed dataset" which I do not see if I go to the same page in incognito (not logged in) mode. So it is embargoed.  
But I think we need to add some more explicit indicator for such datasets. E.g. a lock icon or alike nearby the title to easily discriminate between public and embargoed dandisets in the listing of dandisets. (will also apply to "My dandisets").

**Comment by waxlamp** [comment]
I know I have seen an "embargoed" chip on staging before... @mvandenburgh, can you commenton what might be happening here?

**Comment by mvandenburgh** [comment]
> I know I have seen an "embargoed" chip on staging before... @mvandenburgh, can you commenton what might be happening here?

None of the embargo UI elements are merged to `master` yet, so they are not reflected in https://gui-staging.dandiarchive.org yet. You can see them in this deploy preview though https://deploy-preview-800--gui-dandiarchive-org.netlify.app/

**Comment by waxlamp** [comment]
Ah thanks for clearing that up, @mvandenburgh.

It might be good to unveil the visual indicator and the access restrictions in prod, but keep the UI for creating embargoed dandisets hidden until the CLI catches up.

If we did that in one PR, it would likely be enough to close this issue and Yarik's other issue about 404s on embargoed data.

**Comment by yarikoptic** [comment]
> You can see them in this deploy preview though https://deploy-preview-800--gui-dandiarchive-org.netlify.app/

Cool, but unfortunately I found no embargoed datasets there to see "in action".

**Comment by waxlamp** [comment]
Are you logged in? The very first dandiset in "public dandisets" is embargoed (only if I am logged in).

**Comment by yarikoptic** [comment]
I could have sworn I was logged in.  Tried again -- wasn't, logged in, see red "embargoed".

Cool. Added `Closes` statement to #800
