### ISSUE TITLE
Rename "Public Dandisets" into "All dandisets" or just "Dandisets"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#834]
Since that listing would include embargoed dandisets to which user has access to, and which aren't really "Public".

**Comment by waxlamp** [comment]
I would prefer "all dandisets" to "dandisets".

Need input from @satra.

**Comment by satra** [comment]
i don't have a strong preference, but `all` may mean everything .and we will not be showing embargoed dandisets to non-owners. Hence`Dandisets` without any qualifiers seems simpler, but would be ok if `All` was included.

**Comment by waxlamp** [comment]
The trouble is there's a "my dandisets" tab as well, which is a contrast to "all dandisets". IMO, "all" is implicitly "all that are available to me" which excludes embargoed dandisets.

(I don't want to bikeshed this too much--I'm fine with either choice, but it deserves at least this much discussion)

**Comment by waxlamp** [comment]
The other thing we could consider is not to show embargoed dandisets in the "all/public" tab at all, only in "my". Then we could keep the word "public" in the interface, which is a nice, subtle reminder of what we're all about here in dandiworld.

**Comment by satra** [comment]
> The other thing we could consider is not to show embargoed dandisets in the "all/public" tab at all, only in "my".

i'm good with that as long as admins can see them somewhere.

**Comment by waxlamp** [comment]
My thinking is to show embargoed dandisets only in the "my dandisets" view (both to their owners, and to admins). Then we can retain the "public dandisets" designation which has its benefits.

@satra I assume you're ok with this plan; let me know if not.

**Comment by yarikoptic** [comment]
FWIW, I do not think that "My" includes all embargoed I might have access to.  E.g. on https://deploy-preview-800--gui-dandiarchive-org.netlify.app/#/dandiset (on staging there is no filtering, have pages in My, didn't go through) I see 101126 in "Public" but not listed in "My".

**Comment by satra** [comment]
@waxlamp 's thing has not been implemented yet though. that's why embargoed are in public. he is suggesting a change to the behavior.
