### ISSUE TITLE
Remove Welcome, make logo and/or DANDI in the top "menu" go to the main page

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-archive#837]
ATM on DLP page, e.g. https://gui.dandiarchive.org/#/dandiset/000168/draft, WELCOME is the one which goes to the main page (https://gui.dandiarchive.org/) and logo and DANDI to the left of it aren't hyperlinks.  I wonder if it is worth keeping WELCOME at all -- why not to make "logo DANDI" to be the hyperlink jumping to the main page?  That would save some page real estate happen we need another menu item and IMHO would make UI more effective.

In the narrow (didn't check mobile on the phone) view that "logo DANDI" would not be a part of the drop down menu, so menu would not have a link to the main page, but IMHO that is ok -- it would still be visible and would be clickable as other elements left on top ("New dandiset", profile circle)

**Comment by waxlamp** [comment]
I would be ok with this. @jtomeck, any reason not to do it?

**Comment by jtomeck** [comment]
I think this is a good idea. No issues from me!
