### ISSUE TITLE
embargo data size calculation not working

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#855]
![image](https://user-images.githubusercontent.com/844306/151242767-34763824-8289-4106-bc17-5405ea671670.png)

We have 3 non-empty files in, but it is showing up as 0 B

(this is in staging)

**Comment by waxlamp** [comment]
@bendichter, after this PR deploys to staging (should be just a few minutes) you can check to see whether the problem is fixed. If not, please re-open this issue.

**Comment by bendichter** [comment]
fixed!

![image](https://user-images.githubusercontent.com/844306/151387699-90151603-6e31-4995-af6e-50fd543e1beb.png)
