### ISSUE TITLE
link to associated dandi hub notebooks

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-archive#860]
Right now, on the DANDI Hub, we have notebooks that are associated with dandisets, but there isn't a good way for users to discover them. It would be better to have some sort of link to these dandisets on the DLP.

I noticed this feature just now that could really help here. I don't know if this is new or I just missed it before:

![image](https://user-images.githubusercontent.com/844306/151590052-11c71828-8170-4c7f-aa49-753702564eb8.png)

When you click this, it gives you a link that opens up the notebook. 

What is the best way to add this to the DLP? Should we just add these links as Related Resources, or is there a better way?

**Comment by satra** [comment]
great idea. 

the user can always link this in the additional resources. 

for the DLP level, we should do some reorganization of the dandi-notebooks repo (to clean things up), and point the user directly to that. for example:

[dandiset 108 notebooks](https://hub.dandiarchive.org/hub/user-redirect/lab/tree/dandi-notebooks/000108)

we can even add an README.md that opens directly.

**Comment by satra** [comment]
Related Resources is something we want owners to add and not us at this moment. so they are welcome to. 

however, we also want a way for other users to be able to annotate dandisets in the future. this would allow us or others to add such additional links. this will require some work and we are working on this feature for some other projects. can't give a timeline, but hopefully this year.

**Comment by waxlamp** [comment]
> great idea.
> 
> the user can always link this in the additional resources.
> 
> for the DLP level, we should do some reorganization of the dandi-notebooks repo (to clean things up), and point the user directly to that. for example:
> 
> [dandiset 108 notebooks](https://hub.dandiarchive.org/hub/user-redirect/lab/tree/dandi-notebooks/000108)
> 
> we can even add an README.md that opens directly.

I tried this link just now and I get an error message that it can't start the kernel. I can't tell if this is a general bug on the hub, or if that link has gone stale or changed since the original message.

If a link like that can be generated for each dandiset, we can certainly add it to the DLP.

**Comment by satra** [comment]
> I get an error message that it can't start the kernel

that can happen if no resources are available in the spot pool. do you have the details. open an issue on the hub perhaps? at present it works for me.

more pertinent to this issue, there are many ways to do this, but we have to be consistent about how in dandi we support this.  
- some folks could use jupyterbook and connect to dandi (we did this temporarily for a workshop).
- people should be able to use links to our example notebooks

**Comment by waxlamp** [comment]
> > I get an error message that it can't start the kernel
> 
> that can happen if no resources are available in the spot pool. do you have the details. open an issue on the hub perhaps? at present it works for me.
> 

It has worked or not the last several times I've tried. If I can do a closer examination of the failure mode, I will file an issue.

> more pertinent to this issue, there are many ways to do this, but we have to be consistent about how in dandi we support this.
> 
> * some folks could use jupyterbook and connect to dandi (we did this temporarily for a workshop).
> * people should be able to use links to our example notebooks

I suppose I am missing something. At the DLP level, it is easy to add a link templated after the example link you posted upthread (https://hub.dandiarchive.org/hub/user-redirect/lab/tree/dandi-notebooks/000108) in a special place in each dandiset's DLP. Are we talking about something more difficult or complex than that?

**Comment by waxlamp** [comment]
@satra, @bendichter: where did we land on this? It seems like people could place links to important notebooks right in the "related resource" section of the dandiset metadata. My other idea of autogenerating a link to place in the DLP does not seem actionable at the moment (because not all dandisets have a valid "dandi-notebooks" URL like 108 does).

What is our next action on this? If there's nothing actionable, I'd like to close the issue and address it when it comes up again in a more concrete form.

**Comment by bendichter** [comment]
From my perspective, it would be nice to have a specially formatted "Associated Notebooks" link on the DLP which takes you to a directory of notebooks, or better yet a README.md file that describes the different notebooks available. I suppose it's not critical though since users can add that link as an Associated Resource.
