### ISSUE TITLE
Add manifest location to DLP

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#861]
This was present in the old DLP, but I didn't carry it over in the redesign.

![Screenshot from 2022-01-28 16-04-16](https://user-images.githubusercontent.com/37340715/151621296-1434c88b-074e-496c-96ec-ccb6bcb58663.png)

**Comment by satra** [comment]
i think this could go in the top right corner box or just a link elsewhere or next to the file count as an url link
