### ISSUE TITLE
Add UI link to file issues about a dandiset

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#863]
I don't know the best place for this, but one is to file an issue in the datalad dandisets org corresponding to the dandiset or to the helpdesk issues, with a url packet that adds info about the dandiset. (github now allows such things).

**Comment by satra** [comment]
this perhaps can be a superset of the dandi review button in #698 . github also now allows a little form based interface, so we can be more generic on the UI side and have a form based setup on github to tell users what they want to do.

**Comment by waxlamp** [comment]
In recent discussions we decided to link to the issue thread in the appropriate `dandisets` repository. Is that still a good plan for this?

**Comment by yarikoptic** [comment]
> just make sure when the issues are posted the relevant owners and dandi team are notified via github @ alerts.

for that I guess we need then add (well -- invite) some/all owners of the dandisets on dandiarchive to be able to `Triage` issues on any specific dandiset repo.  I am not sure though if that would be enough to have them "subscribed" to that repo.  Alternatively we could make it "opt-in" (just announce via email) that repository 000XXX was created and invite them to subscribe (but then better first check if they aren't subscribed already).  I guess that should be done as part of the https://github.com/dandi/dandisets/tree/draft/tools/backups2datalad .

- I don't think we should do that per each zarr repo at https://github.com/dandizarrs (those are linked as subdatasets into corresponding dandisets)
- 
PS and we would need to have a little helper script to do that for already existing repos

**Comment by satra** [comment]
can't we just add `@owner1 @owner2 ... @dandi/archive-admin` to the issue template when filing the issue since we have that info in the DLP?

**Comment by yarikoptic** [comment]
indeed we could, but that would mean that if someone just goes to github issues page and files an issue, corresponding "owners" would not necessarily be notified (unless we maintain/update .github/ISSUE_TEMPLATE or whatever it is per each dandiset -- even more hassle IMHO)

**Comment by satra** [comment]
when i say issue template, all of this can happen via url to open new issue. you can inject into body of message. so when someone files issue they automatically inform owners and dandi admins (this part i'm not sure). if they remove those lines then obviously no notification.

here is an example:

https://github.com/dandisets/000026/issues/new?labels[]=People%20Management&labels[]=[Type]%20Bug&title=Issue:&milestone=People%20Management:%20m6&assignee=satra&body=This%20is%20a%20prefilled%20issue

i copied it from something else, so not all sections adjusted.

**Comment by yarikoptic** [comment]
I got that. And I was talking about "New issue" button people would still be able to press on github interface, such as e.g. from https://github.com/dandisets/000108/issues page

**Comment by satra** [comment]
i think very few people would do that if there was a direct interface from the DLP. it's not easy to navigate that dandisets repo. and we can push a github template into it the dandiset programmatically that contains the owners if we wanted to.

**Comment by waxlamp** [comment]
I think, at least to start, @satra's plan for injecting at-mentions for the dandiset owners is a good plan.

**Comment by yarikoptic** [comment]
The question has came in slack debug channel so I guess we should prioritize development of this.  I will propose today/tomorrow a brief design doc to ease discussion.

**Comment by yarikoptic** [comment]
Let's continue to iron out a possible quick implementation on https://github.com/dandi/dandi-archive/pull/1595

**Comment by waxlamp** [comment]
Closing in favor of #1595.
