### ISSUE TITLE
Investigate node package for bucket to bucket copy efficiency

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#868]
@AlmightyYakob - since this is about bucket to bucket copy you may want to look at what [this node package](https://github.com/generalui/s3p) did to increase efficiency.  the numbers are impressive, hence good to consider what the details were and perhaps write a python equivalent. i'm just putting this here as an information point more than holding up #830.

**Comment by waxlamp** [comment]
Rather than translate to Python, we should prefer simply using S3P directly where needed.

**Comment by satra** [comment]
for bucket to bucket copy instead use [s5cmd](https://github.com/peak/s5cmd) written in go with significantly faster throughput.

**Comment by waxlamp** [comment]
Since
1. AWS provides its own native bucket to bucket copy operation, and
2. We are redesigning embargo not to need this operation anymore

I believe this can be closed.

**Comment by satra** [comment]
@waxlamp - if you can point to which aws operation does this as fast that would be good to have encoded in the issue. i believe all of these tools use the native api and parallelize them.
