### ISSUE TITLE
500 error when searching for github id in user admin panel

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#874]
go to the [user admin panel](https://api.dandiarchive.org/admin/auth/user/), enter a user id (e.g., waxlamp) and click on search.

**Comment by satra** [comment]
reopening. any search on this page leads to a 500 error.

**Comment by satra** [comment]
i have tried first name and email.

**Comment by dchiquito** [comment]
I think this will be resolved with a release https://github.com/dandi/dandi-archive/releases/edit/untagged-4ff5432592077c6db8b1
