### ISSUE TITLE
Cancel zarr uploads asynchronously

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#887]
Right now trying to cancel an upload to a zarr file tries to delete any uploaded files to S3 in band, which hits the Heroku request timeout for reasonably large batches. We should instead do that in an asynchronous task and lock the zarr until cancel is complete.

**Comment by AlmightyYakob** [comment]
Steps seem to be:

* Client calls upload cancel endpoint
* Zarr detail get endpoint exposes the `active_uploads` property on the zarr model
* Client queries the detail get endpoint until the zarr is unlocked, and once it is, can do more uploads
