### ISSUE TITLE
DRF UI no longer shown for Asset endpoints

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#917]
Endpoints that are part of the asset viewset no longer render the DRF HTML page and instead return raw JSON. Example https://api-staging.dandiarchive.org/api/dandisets/101233/versions/draft/assets/7e10c90b-3189-4608-91c2-5350273d4820/

(reported by @satra)

`git bisect` indicates [this commit](https://github.com/dandi/dandi-archive/commit/6be0088d079cf9dd7c766c17df19ed4b8ef096c2) broke it.

**Comment by satra** [comment]
hey folks, i don't think this is fixed yet in production.

**Comment by AlmightyYakob** [comment]
> hey folks, i don't think this is fixed yet in production.

Yes we haven't released since this was merged. Is this pressing?

**Comment by satra** [comment]
it's nicer to look at and we are debugging some metadata issues with samples, and i wanted to simply point at the asset metadata, but not in it's current form.

**Comment by AlmightyYakob** [comment]
@satra This is now in production.
