### ISSUE TITLE
DANDI logo isn't displayed in Firefox

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-archive#933]
The DANDI logo that links back to the home page doesn't show up if viewing the site with Firefox. It displays correctly with chromium-based browsers though (tested with brave and google chrome)

![Screenshot from 2022-03-01 14-50-12](https://user-images.githubusercontent.com/37340715/156238447-352ad415-7eae-4b7b-9f2a-0ef5b1a044ca.png)

**Comment by satra** [comment]
i get this in chrome as well but under specific width settings.

**Comment by yarikoptic** [comment]
FWIW confirming the issue on firefox 91.5.0esr (64-bit) on debian gnu linux
