### ISSUE TITLE
Calculate zarr checksums out of band

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-archive#954]
- Remove zarr checksum updates from the completion endpoint
- Add a new endpoint `/zarr/{zarr_id}/ingest/` that recomputes the entire checksum
  - Add a new status field that has states:
    - `PENDING` when the checksum is known to be incorrect. Modifying the zarr archive in any way resets the state to this.
    - `CALCULATING`/`INGESTING`/`?` when the task is in progress. Set when the `/ingest/` endpoint is called. Block uploads while in this state.
    - `VALID`/`?` when the checksum is computed and up to date.
  - Call the existing ingestion script
  - Add `status` to the ZarrSerializer so that CLI can poll it

**Comment by AlmightyYakob** [comment]
It's clear that if ingestion is ongoing, any zarr write operation should be denied. However, going the other way, if there are any active uploads for a zarr, should ingestion be disabled, pending those uploads being either completed or cancelled? It seems to me the answer is yes.

**Comment by yarikoptic** [comment]
> It's clear that if ingestion is ongoing, any zarr write operation should be denied.

if so --  probably 503 with `Retry-After`.  But I wonder if it should be denied -- if user is to upload, and denied, it means only that client needs to wait until no longer denied and write then, thus immediately invalidating just finished ingestion.  May be request for "write operation" should just cancel ongoing ingestion, or leave some other mark which would invalidate it upon completion so no checksum is stored.  E.g. if there is a timestamp for when zarr ingestion started, and there is a timestamp for when write operation is requested, then ingestion process can simply not write zarr checksum if timestamp for write is later than for ingestion (and remove ingestion timestamp).

> However, going the other way, if there are any active uploads for a zarr, should ingestion be disabled, pending those uploads being either completed or cancelled? It seems to me the answer is yes.

agree with that!
