### ISSUE TITLE
add warning to validation for no mentioned funding

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#957]
many users don't know how to add funding, or overlook that section. this could be improved in a few ways. 

1. validation adds warnings for things we expect (we can update the dandischema code to do so)
2. a little help icon next to each main label on the DLP (shown only to owners of dandisets). so the funding section could say: "To add funding open the metadata editor, choose contributors, and add an organization, with role Funder, and the award number".

perhaps we can come up with a set of these elements and phrases to guide submitters.

**Comment by waxlamp** [comment]
> many users don't know how to add funding, or overlook that section. this could be improved in a few ways.
> 
> 1. validation adds warnings for things we expect (we can update the dandischema code to do so)

This would mean adding a "warning" class to the validation result types (in addition to the already existing "error" class), is that right?

Also: is there a dandischema issue related to this? (If so, I'd like to link to it here.)

> 2. a little help icon next to each main label on the DLP (shown only to owners of dandisets). so the funding section could say: "To add funding open the metadata editor, choose contributors, and add an organization, with role Funder, and the award number".
> 

Would this always appear, or only when specific conditions are met (e.g., funding is blank)?

> perhaps we can come up with a set of these elements and phrases to guide submitters.

Good idea. Have you noticed other common deficiencies in folks' dandisets?

**Comment by satra** [comment]
i think the other issue on adding an edit/info button #1112  and the already merged #310 addresses this. i'm going to close in favor of following up on #1112
