### ISSUE TITLE
Investigate zarr upload complete endpoint with varying file sizes

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandi-archive#980]
> I tested uploading a 38 GB Zarr to staging using dandi 0.37.0.  This took 44 minutes; compare [the previous test](https://github.com/dandi/dandi-cli/pull/923#discussion_r814188637), which took 63 minutes.
>
> * Approximately the first 90 seconds were spent traversing the Zarr filetree
> * The calls to `/upload/complete/` started out very quick, but as the files in each batch grew in size, it started taking up to about 7 seconds.
> * The ingestion at the end took about a minute and a half.

_Originally posted by @jwodder in https://github.com/dandi/dandi-cli/issues/938#issuecomment-1077649082_

**Comment by satra** [comment]
@waxlamp - i'm putting this as severity important, but we should discuss priorities and complexities.

**Comment by satra** [comment]
i'm not sure the 7s completion call time has been resolved. can some provide an update on the time of update completion request?

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob, @danlamanna, can you comment on whether this should be closed?

Checksums are no longer handled / modified directly as a part of upload/complete, so that might have resolved the variance of the endpoint response time.

> i'm not sure the 7s completion call time has been resolved. can some provide an update on the time of update completion request?

Currently as a part of that endpoint, we verify that all uploaded files match the provided checksum when requesting the presigned urls. Since this involves making hundreds of requests to S3, the endpoint will certainly take seconds to complete. Until we change how we handle this (likely by pushing this responsibility onto S3 directly), this behavior isn't fixable.

**Comment by satra** [comment]
just to be clear, we are talking about a single upload completion, so we are talking objects of that upload packet, right? @jwodder confirmed that this is 255 urls. 
- are you doing checksum computation or checking that the object exists? 
- isn't the presigned-url enforcing md5 content? and if so the path cannot exist if it wasn't uploaded properly, right? and unless md5 matches, aws will throw an error.

hence, isn't the only check necessary that the path exists? 

7s still seems very long for confirming that 255 objects exist, and a check which could be done asynchronously.

**Comment by AlmightyYakob** [comment]
> just to be clear, we are talking about a single upload completion, so we are talking objects of that upload packet, right? @jwodder confirmed that this is 255 urls.

Yes

> * are you doing checksum computation or checking that the object exists?

The latter

> * isn't the presigned-url enforcing md5 content? and if so the path cannot exist if it wasn't uploaded properly, right? and unless md5 matches, aws will throw an error.

The presigned URL is **not** enforcing content md5 checksum. If it were, these checks wouldn't be needed. That is something we could (and I'm proposing should) do, to remove this responsibility from the server.

> hence, isn't the only check necessary that the path exists?

Currently it both checks etag (md5) match and object existence, although doing both doesn't incur any extra performance hit since both data are returned in the same request.

> 7s still seems very long for confirming that 255 objects exist, and a check which could be done asynchronously.

Doing this asynchronously would improve things, but it would increase the complexity somewhat, as doing asynchronous things in django natively is problematic. We would probably need to dynamically spin up many threads, and in general doing this within a django request should be avoided. This isn't even considering the fact that any of these requests could randomly fail.

So yeah IMO if we can we should push this responsibility onto S3, and remove these checks from the upload completion endpoint, as it's not really enforcing anything useful. Ingestion still needs to be done after the fact, and so no assumptions are made in the meantime.

But if we're going to keep these checks in that endpoint, you should expect response time on the order of seconds.

**Comment by satra** [comment]
> The presigned URL is not enforcing content md5 checksum.

this is where i thought the zarr upload was different from regular uploads. since the request for upload requires an etag, i thought it was returning a pre-signed url with the content restriction. (we had definitely talked about this multiple times with daniel when the original implementation was made. perhaps @jwodder or @yarikoptic remembers more about this).

but it does seem that would be the simplest change to make if it's not already there. you are getting the list of etags when the client requests pre-signed urls, hence you can generate a pre-signed url with the content restriction in place. and then just check that the object exists. i don't know if making an api call to s3 can be faster than 27ms.

regarding async, that seems like a pity, but i don't know django well enough myself to say if just the check, without any db operation could not be made asynchronous even with exception handling of a request failure (which would be required anyway whether synchronous or asynchronous).

**Comment by waxlamp** [comment]
With the Zarr upload overhaul, this should also be resolved (please re-open if there is a lingering issue here).
