### ISSUE TITLE
styling is off in a "normal" view

### ISSUE THREAD

**Issue by satra** [dandi/dandi-archive#992]
posting a screenshot to show there are a few styling elements that are still required on the front page:
- icon disappears still (this issue was closed) #934
- id circle and create dandiset wrap around #934
- search box extends (i think there is an issue open for this) #936 

the viewport is slightly over half my display width (on a 16" mac), so portrait, but not a narrow view).

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/184063/160952534-7d5ec2d0-3333-4621-8e6c-05fb622f571f.png">

**Comment by waxlamp** [comment]
@mvandenburgh, would you mind triaging this issue? That would entail reproducing the specific UX bugs, then reopening and/or opening new issues to track these things.

**Comment by mvandenburgh** [comment]
We have two open issues that capture these issues (#934 and #936) - I've triaged both of them and added one to the current sprint.

**Comment by waxlamp** [comment]
Do you think Jared help with #934? (Looking for a way to address it sooner rather than later.)

**Comment by mvandenburgh** [comment]
> Do you think Jared help with #934? (Looking for a way to address it sooner rather than later.)

Most likely. It's going to be basically all responsive design work, which I'm not well versed in. I'm happy to dive in and learn myself, but if we want this fixed ASAP it would probably be helpful to involve Jared.

**Comment by waxlamp** [comment]
Thanks, I've pinged Jared and we'll see if he's available to help.

**Comment by waxlamp** [comment]
Closing in favor of #934 and #936.
